F/348-change-workload-generation-buttons
hyrise/Cockpit pull request #374
Opened 2020-03-19 12:44 UTC by kathwill

# Resolves #348 #353 

**Does your pull request solve a problem? Please describe:**  
You should be able to load only one workload at a time and the frequency should be changed when the slider is clicked.

**Does your pull request add a feature? Please describe:**  
There are now radio buttons for loading the workload.

**Affected Component(s):**  
`Frontend`

2020-03-24 13:02 UTC, schTi requested changes

2020-03-24 13:02 UTC, schTi commented on hyrisecockpit/frontend/src/components/workload/WorkloadGeneration.vue
> +              class="mt-0 pt-0"
class should be always at the top to keep a good structure

2020-03-24 13:02 UTC, schTi commented on hyrisecockpit/frontend/src/components/workload/WorkloadGeneration.vue
> +    setInterval(updateWorkloadInformation, 3000);
damn, thats really a big function, which definitely needs improvement. Can you please tell me in a few words, whats going on here?

2020-03-24 13:02 UTC, schTi commented on hyrisecockpit/frontend/src/components/workload/WorkloadGeneration.vue
> +        var loadedWorkloadData: Workload[] = [];
please use always `let` instead of `var`

2020-03-24 13:02 UTC, schTi commented on hyrisecockpit/frontend/src/components/workload/WorkloadGeneration.vue
> +                delete loadedWorkloadData[j];
what is this doing?

2020-03-24 13:02 UTC, schTi commented on hyrisecockpit/frontend/src/components/workload/WorkloadGeneration.vue
> +        for (var i = 0; i < response.data.length; i++) {
for loops are always a bad option. In my opinion you can improve this by using something like `Object.values` or `Object.entries` here. Additionally you should prefer forEach loops, because they improve the readability.

2020-03-26 11:32 UTC, MaxSchneider1337 requested changes

2020-03-26 11:32 UTC, MaxSchneider1337 commented on hyrisecockpit/frontend/src/components/workload/WorkloadGeneration.vue
> +          if (response.data[i].database_blocked_status == 0) {
please use `===` for comparison

2020-03-26 11:32 UTC, MaxSchneider1337 commented on hyrisecockpit/frontend/src/components/workload/WorkloadGeneration.vue
> +        if (loadingCount == response.data.length) {
`===`

2020-03-26 11:32 UTC, MaxSchneider1337 commented on hyrisecockpit/frontend/src/components/workload/WorkloadGeneration.vue
> +        var loadedWorkloadData: Workload[] = [];
cause you declared the result as an empty array I would suggest even using map, reduce here

2020-03-26 11:32 UTC, MaxSchneider1337 commented on hyrisecockpit/frontend/src/components/workload/WorkloadGeneration.vue
> +                delete loadedWorkloadData[j];
also please don't use the delete array function, just create an full array and put it in workload data

2020-03-31 07:09 UTC, schTi approved these changes
Good job! If everything works as expected, it is ready for merge in my opinion!

2020-03-31 11:26 UTC, MaxSchneider1337 approved these changes
good job

2020-03-31 13:47 UTC, merged