f/ fix timestamps formatting
hyrise/Cockpit pull request #460
Opened 2020-03-30 15:43 UTC by MaxSchneider1337

# Resolves #458 and #457 

**Does your pull request solve a problem? Please describe:**  
fixes timestamp locale and formatting

**Affected Component(s):**  
Frontend

2020-03-30 15:48 UTC, schTi requested changes

2020-03-30 15:48 UTC, schTi commented on hyrisecockpit/frontend/src/components/details/TimeInterval.vue
> +x<template>
???

2020-03-31 09:35 UTC, MaxSchneider1337 commented on hyrisecockpit/frontend/src/components/details/TimeInterval.vue
> +x<template>
wtf

2020-03-31 10:24 UTC, schTi approved these changes

2020-03-31 10:31 UTC, merged