fixing bug with changing database color
hyrise/Cockpit pull request #476
Opened 2020-04-02 16:29 UTC by kathwill

# Resolves #456 

**Does your pull request solve a problem? Please describe:**  
The database color changes when starting the frontend, reloading or adding a database.

**Does your pull request add a feature? Please describe:**  
There are now consistent colors for the database instances.

**Affected Component(s):**  
`Frontend`

2020-04-06 14:47 UTC, schTi requested changes

2020-04-06 14:47 UTC, schTi commented on hyrisecockpit/frontend/src/meta/colors.ts
> +export const databaseColorDefinition: Record<string, any> = {
Im not sure if this is what we really wanted here. You just hardcoded some IDs, but when using a different ID the ID will not be persistent. But I am not sure if we really want to have persistent coloring. What do you think @MaxSchneider1337?

2020-04-06 15:27 UTC, kathwill commented on hyrisecockpit/frontend/src/meta/colors.ts
> +export const databaseColorDefinition: Record<string, any> = {
I thought we wanted persistant coloring for our default instances. Otherwise we would  need to know all the IDs that were used before

2020-04-06 15:43 UTC, schTi commented on hyrisecockpit/frontend/src/meta/colors.ts
> +export const databaseColorDefinition: Record<string, any> = {
No we could use a hash function which will always assign an ID to the same color

2020-04-06 18:03 UTC, MaxSchneider1337 commented on hyrisecockpit/frontend/src/meta/colors.ts
> +export const databaseColorDefinition: Record<string, any> = {
Persistent coloring was requested so we definitely need it. I would also suggest using an hash function to determine the color for a database

2020-04-07 13:58 UTC, schTi requested changes

2020-04-07 13:58 UTC, schTi commented on hyrisecockpit/frontend/src/services/databaseService.ts
> +    const hashedDatabaseID = require("crypto")
The npm crypto package is deprecated, please move to crypto-js instead.

2020-04-07 13:58 UTC, schTi commented on hyrisecockpit/frontend/src/services/databaseService.ts
> +    const hashedDatabaseID = require("crypto")
As I think you need to include the new package to the dev dependencies before using it.

2020-04-08 08:58 UTC, Bouncner commented on hyrisecockpit/frontend/src/services/databaseService.ts
> +    let color = Object.values(colorDefinition)[index];
Sorry for these direkt comments. Github is a mess.

I asked if makes sense to use the host name, but I am rather asking for hostname+port.

2020-04-08 09:17 UTC, kathwill commented on hyrisecockpit/frontend/src/services/databaseService.ts
> +    let color = Object.values(colorDefinition)[index];
We are using the ID of the database here. You can specify it when adding a database (the default is the hostname, e.g. "vm-york", ...)

2020-04-08 12:41 UTC, Bouncner commented on hyrisecockpit/frontend/src/services/databaseService.ts
> +    let color = Object.values(colorDefinition)[index];
What happens if we have two instances on the same node?
How is this database ID determined?

2020-04-08 13:25 UTC, schTi commented on hyrisecockpit/frontend/src/services/databaseService.ts
> +    let color = Object.values(colorDefinition)[index];
It is not possible to add two instances with the same ID. You have to change the ID manually before adding the new instance.

2020-04-08 14:34 UTC, Bouncner commented on hyrisecockpit/frontend/src/services/databaseService.ts
> +    let color = Object.values(colorDefinition)[index];
Do you have screenshot of the add-instance-screen at hand?

2020-04-08 15:38 UTC, schTi commented on hyrisecockpit/frontend/src/services/databaseService.ts
> +    let color = Object.values(colorDefinition)[index];
![image](https://user-images.githubusercontent.com/49444254/78803809-ba53f400-79bf-11ea-9ba7-1a4a79a66652.png)

2020-04-08 16:38 UTC, Bouncner commented on hyrisecockpit/frontend/src/services/databaseService.ts
> +    let color = Object.values(colorDefinition)[index];
The port is hidden in advanced?
And you default the database id to the host name?

2020-04-08 16:46 UTC, schTi commented on hyrisecockpit/frontend/src/services/databaseService.ts
> +    let color = Object.values(colorDefinition)[index];
Yes exactly. When typing the host field, it will automatically add this input to the ID field., until you manually change the ID

2020-04-14 15:31 UTC, schTi approved these changes

2020-04-14 18:00 UTC, merged

2020-04-14 18:17 UTC, Bouncner commented
I am surprised that this was merged even though there are still a lot of unresolved issues.

2020-04-14 18:18 UTC, Bouncner commented on hyrisecockpit/frontend/src/services/databaseService.ts
> +    let color = Object.values(colorDefinition)[index];
How do you determine that two instances do not get the same color index?

2020-04-14 18:18 UTC, Bouncner commented on hyrisecockpit/frontend/src/services/databaseService.ts
> +      hashedDatabaseID =
Explanation?

2020-04-14 18:18 UTC, Bouncner commented on hyrisecockpit/frontend/src/services/databaseService.ts
> +    let color = Object.values(colorDefinition)[index];
Ok, got it.

2020-04-15 10:07 UTC, MaxSchneider1337 commented on hyrisecockpit/frontend/src/services/databaseService.ts
> +    let color = Object.values(colorDefinition)[index];
@kathwill I already ran into that problem I think.

2020-04-15 10:20 UTC, MaxSchneider1337 commented
@kathwill please resolve all conservations and answer all questions before merging the pr

2020-04-20 10:02 UTC, Bouncner commented on hyrisecockpit/frontend/src/services/databaseService.ts
> +    let color = Object.values(colorDefinition)[index];
@MaxSchneider1337 : can you please open an issue for that? @kathwill: can you take that issue and make a recommendation how to approach this problem? It's not trivial. We should discuss this.