provide renaming tool
hyrise/Cockpit pull request #495
Opened 2020-04-07 14:03 UTC by caterinamandel98

# Resolves #493 

**Does your pull request solve a problem? Please describe:**  
At the moment we struggle with overlapping table names in different workloads. With this pr we solve the problem by providing a tool, which makes it possible to rename tables in query files.

**Affected Component(s):**  
`Workloads`

2020-04-08 14:02 UTC, PeterTsayun approved these changes

2020-04-09 10:39 UTC, heseding requested changes

2020-04-09 10:39 UTC, fabianhe commented on utils/benchmark_renaming_tool/replacer.py
> +            )
This would replace a column with the same name as a table as well.

2020-04-26 10:04 UTC, PeterTsayun commented on utils/benchmark_renaming_tool/replacer.py
> +        queries = queries.replace(f" {old_table_name}.", f" {new_table_name}.")
Here is the duplicated code, isn't it?

2020-04-26 10:04 UTC, PeterTsayun commented on utils/benchmark_renaming_tool/replacer.py
> +        queries = queries.replace(f"AS {new_table_name}", f"AS {old_table_name}")
Shouldn't the `new_table_name` and `old_table_name` be switched?
Moreover, isn't that the special case of 
```
queries.replace(f" {old_table_name}.", f" {new_table_name}.")
```
?

2020-04-28 10:59 UTC, Alexander-Dubrawski commented on utils/benchmark_renaming_tool/replacer.py
> +        queries = queries.replace(f" {old_table_name}.", f" {new_table_name}.")
Obviously yes 😄 .

2020-04-28 11:06 UTC, Alexander-Dubrawski commented on utils/benchmark_renaming_tool/replacer.py
> +        queries = queries.replace(f"AS {new_table_name}", f"AS {old_table_name}")
No. For `tpcds` we need to rename the aliases back. One example is the Query with the number 31.

2020-04-28 11:51 UTC, heseding commented on utils/benchmark_renaming_tool/replacer.py
> +from utils.benchmark_renaming_tool.table_names import table_names as tables
Can we use the `table_names` at `hyrisecockpit/database_manager/table_names.py` instead of duplicating the file?

2020-05-04 07:46 UTC, heseding approved these changes

2020-05-04 07:46 UTC, fabianhe commented on utils/benchmark_renaming_tool/replacer.py
> +        except BaseException:
```suggestion
        except NotExistingWorkloadFolderException:
```

2020-05-04 07:46 UTC, fabianhe commented on utils/benchmark_renaming_tool/replacer.py
> +        return rep
```suggestion
        return {table: f"{table}_{self.workload}_{self.scale}" for table in tables[self.workload]}
```

2020-05-05 06:24 UTC, merged