Rename tables in queries
hyrise/Cockpit pull request #498
Opened 2020-04-08 09:23 UTC by caterinamandel98

# Resolves #493 

**Does your pull request solve a problem? Please describe:**  
At the moment we struggle with overlapping table names and aren't able to execute different workloads at the same time due to that. In this pr, we rename the table names in the queries in order to solve that problem.

**Affected Component(s):**  
`Workloads`

2020-04-08 11:09 UTC, heseding reviewed
Why do we need to rename `job` to `job_1`?

2020-04-09 10:34 UTC, heseding requested changes

2020-04-09 10:34 UTC, fabianhe commented on hyrisecockpit/workload_generator/workloads/workload_queries/job_1/10a.sql
> +		AND ct.id = mc.company_type_job_1_id;
As far as I understand, the table `movie_companies` is renamed `movie_companies_job_1` with this PR. In this query, it is selected from with an `AS` renaming it `mc`.
`movie_companies` has a column called `company_type_id`, but since there is a table called `company_type` (which is renamed `company_type_job_1`) we rename the column `company_type` as well, which shouldn't be the case.

2020-04-15 15:23 UTC, Alexander-Dubrawski commented on hyrisecockpit/workload_generator/workloads/workload_queries/job_1/10a.sql
> +		AND ct.id = mc.company_type_job_1_id;
You are completely right. We need to fix that.

2020-04-16 14:46 UTC, Bouncner commented on hyrisecockpit/workload_generator/workloads/workload_queries/job_1/10a.sql
> +		AND ct.id = mc.company_type_job_1_id;
At least this case looks doable.

2020-04-16 19:27 UTC, caterinamandel98 commented on hyrisecockpit/workload_generator/workloads/workload_queries/job_1/10a.sql
> +		AND ct.id = mc.company_type_job_1_id;
This case is definitively doable, yet, we don't want to rely on this case being the only one.

2020-04-24 11:10 UTC, heseding requested changes

2020-04-24 11:10 UTC, fabianhe commented on hyrisecockpit/workload_generator/workloads/job_1/6a.sql
> +SELECT MIN(k.keyword) AS movie_keyword_job_1, MIN(n.name) AS actor_name, MIN(t.title) AS marvel_movie
This should not be renamed:
```suggestion
SELECT MIN(k.keyword) AS movie_keyword, MIN(n.name) AS actor_name, MIN(t.title) AS marvel_movie
```

2020-04-24 11:10 UTC, fabianhe commented on hyrisecockpit/workload_generator/workloads/tpch_0_1/08.sql
> +		(SELECT SUBSTR(o_orderdate, 1, 4) AS o_year, l_extendedprice * (1 - l_discount) AS volume, n2.n_name AS nation_tpch_0_1
This should not be renamed:

```suggestion
		(SELECT SUBSTR(o_orderdate, 1, 4) AS o_year, l_extendedprice * (1 - l_discount) AS volume, n2.n_name AS nation
```

2020-04-27 13:51 UTC, heseding approved these changes

2020-04-28 13:16 UTC, merged