f/440 plugin activity in charts
hyrise/Cockpit pull request #500
Opened 2020-04-08 12:34 UTC by MaxSchneider1337

# Resolves #440

**Does your pull request add a feature? Please describe:**  
show plugin activity in charts.  

**Affected Component(s):**  
Linechart ,Frontend

**Additional context:**  
Add any other context or screenshots about the pull request here.

2020-04-08 12:35 UTC, MaxSchneider1337 commented on hyrisecockpit/frontend/src/components/charts/Linechart.vue
> +          y: [[props.maxValue + 1]],
this makes problems if the max-value changes

2020-04-08 12:42 UTC, MaxSchneider1337 commented on hyrisecockpit/frontend/src/components/charts/Linechart.vue
> +        },
add hoverinfo

2020-04-08 12:43 UTC, MaxSchneider1337 commented on hyrisecockpit/frontend/src/components/charts/Linechart.vue
> +          ...Object.values(props.selectedDatabases).map(id => props.data[id])
this can probably be reset to the previous version

2020-05-06 09:10 UTC, schTi requested changes

2020-05-06 09:10 UTC, schTi commented on hyrisecockpit/frontend/src/components/charts/Linechart.vue
> +                [1]
Can you maybe use a function for that? This would make the whole code more descriptive

2020-05-06 09:10 UTC, schTi commented on hyrisecockpit/frontend/src/components/metrics/Latency.vue
> +      :pluginEventData="pluginEventData"
Do we just want to show the plugin event data in latency and throughput graphs?

2020-05-06 09:32 UTC, MaxSchneider1337 commented on hyrisecockpit/frontend/src/components/metrics/Latency.vue
> +      :pluginEventData="pluginEventData"
At least the issue says so :D But we should probably ask our supervisors

2020-05-06 09:42 UTC, Bouncner commented on hyrisecockpit/frontend/src/components/metrics/Latency.vue
> +      :pluginEventData="pluginEventData"
I need to see them. Spontaneously, I’d say all time-based graphs since the compression plugin actions, e.g., are super interesting for the DRAM line chart.

2020-05-06 12:29 UTC, schTi approved these changes
Thanks for the changes. Good job :fire:

2020-05-06 12:40 UTC, merged