f/501 adapt to new workload names
hyrise/Cockpit pull request #502
Opened 2020-04-08 13:19 UTC by MaxSchneider1337

# Resolves #501

**Does your pull request solve a problem? Please describe:**  
new workload names in backend

**Does your pull request add a feature? Please describe:**  
adapt frontend to new names

**Affected Component(s):**  
frontend

2020-04-08 13:28 UTC, schTi approved these changes
Good one! Nice, that you fixed the tests, too :fire:

2020-04-09 08:34 UTC, MaxSchneider1337 commented
depends on backend branch #498 #499

2020-04-19 18:37 UTC, MaxSchneider1337 commented
@Alexander-Dubrawski I just noticed you closed the backend prs for this issue. Can this be closed as well?

2020-04-24 07:55 UTC, kathwill requested changes
I think it is not necessary to change our intern names for the workloads to the backend names. Can you please change that?

2020-04-24 07:55 UTC, kathwill commented on hyrisecockpit/frontend/src/components/workload/WorkloadGeneration.vue
> +      job_1: false
Why did you change these names too? These are just our intern names that don't need to be changed

2020-04-24 07:55 UTC, kathwill commented on hyrisecockpit/frontend/src/components/workload/WorkloadGeneration.vue
> +          switchesLoading.job_1
It's the same over here

2020-04-24 07:55 UTC, kathwill commented on hyrisecockpit/frontend/src/meta/workloads.ts
> +  tpch_0_1: {
See my other comment. I think you should only change the transferred strings

2020-04-24 07:55 UTC, kathwill commented on hyrisecockpit/frontend/src/types/workloads.ts
> +export type Workload = "tpch_0_1" | "tpch_1" | "tpcds_1" | "job_1";
See my other comment

2020-04-24 07:55 UTC, kathwill commented on hyrisecockpit/frontend/src/types/workloads.ts
> +  "job_1"
Same here

2020-04-24 12:14 UTC, MaxSchneider1337 commented on hyrisecockpit/frontend/src/components/workload/WorkloadGeneration.vue
> +      job_1: false
Different names would be al hell to maintain. Imagine a new person working on this project. He/She would never know where which separator has to be used

2020-04-24 13:31 UTC, kathwill commented on hyrisecockpit/frontend/src/components/workload/WorkloadGeneration.vue
> +      job_1: false
No, it's not. Currently you only need to change 1 file (the file in which the backend workload names are defined), but you changed 3. We started with this because we don't want a mixture of camelcase and underscore. So I don't see why we should lose that. (And even if we decided to use underscore you would need to change more than the files you changed)

2020-04-27 08:59 UTC, MaxSchneider1337 commented
closed due to too old origin branch --> new #558

2020-04-27 08:59 UTC, closed without merging