F/511 reformat line chart
hyrise/Cockpit pull request #517
Opened 2020-04-14 14:28 UTC by MaxSchneider1337

# Resolves #511

**Does your pull request solve a problem? Please describe:**  
improve design for the linecharts.

**Does your pull request add a feature? Please describe:**  
zero

**Affected Component(s):**  
Frontend, Linechart, Tile 

**Additional context:**  
zero

2020-04-14 15:23 UTC, MaxSchneider1337 commented
this is how it looks like
![image](https://user-images.githubusercontent.com/38442947/79242451-a6533b00-7e74-11ea-956e-7bd5e0e9f8be.png)

2020-04-14 15:26 UTC, schTi requested changes

2020-04-14 15:26 UTC, schTi commented on hyrisecockpit/frontend/src/components/charts/Linechart.vue
> +      fill: "tonexty",
Color should only be filled on comparison page, right?

2020-04-14 15:28 UTC, MaxSchneider1337 commented on hyrisecockpit/frontend/src/components/charts/Linechart.vue
> +      fill: "tonexty",
looks great on overview as well

2020-04-14 15:59 UTC, schTi commented on hyrisecockpit/frontend/src/components/charts/Linechart.vue
> +      fill: "tonexty",
Okay, can you add a screen shot of it?

2020-04-14 18:20 UTC, Bouncner commented on hyrisecockpit/frontend/src/components/charts/Linechart.vue
> +      fill: "tonexty",
And can you please check how that looks with more than 3 databases? Sample images from anywhere would be sufficient for me.

2020-04-14 18:33 UTC, MaxSchneider1337 commented on hyrisecockpit/frontend/src/components/charts/Linechart.vue
> +      fill: "tonexty",
compare: 
![image](https://user-images.githubusercontent.com/38442947/79260782-1cfd3200-7e8f-11ea-93f2-5926fa716e43.png)

overview: 
![image](https://user-images.githubusercontent.com/38442947/79260849-38683d00-7e8f-11ea-8bd4-d900dcd45845.png)

2020-04-14 18:39 UTC, MaxSchneider1337 commented on hyrisecockpit/frontend/src/components/charts/Linechart.vue
> +      fill: "tonexty",
![image](https://user-images.githubusercontent.com/38442947/79261112-a6146900-7e8f-11ea-86a9-262a5ec66199.png)
4 dbs break the format, but the plots seem to be too small anyway. I would suggest limiting the number of dbs on the comparison site to 3.

2020-04-14 18:44 UTC, Bouncner commented on hyrisecockpit/frontend/src/components/charts/Linechart.vue
> +      fill: "tonexty",
I agree that 4 is quite a lot, but the formatting should not be an issue with "a responsive" design, shouldn't it?

For the overview, I think the default line chart is a better fit.

2020-04-14 18:46 UTC, MaxSchneider1337 commented on hyrisecockpit/frontend/src/components/charts/Linechart.vue
> +      fill: "tonexty",
4 dbs also breaks the system info
![image](https://user-images.githubusercontent.com/38442947/79262079-0526ad80-7e91-11ea-94c8-a0f4040fc89c.png)

2020-04-14 18:50 UTC, MaxSchneider1337 commented on hyrisecockpit/frontend/src/components/charts/Linechart.vue
> +      fill: "tonexty",
@Bouncner sadly even most responsive designs break on a minimal with. We could also limit the max dbs according to the screen with. There should be enough space on a 4k screen, for 4 dbs.

2020-04-14 20:12 UTC, Bouncner commented on hyrisecockpit/frontend/src/components/charts/Linechart.vue
> +      fill: "tonexty",
I don't expect you to fit 17 databases into a single row. But the last picture of the instance view showed a case which should be managable when the database button, the title, and the metric each get their own row (or 2 and 1 on two rows). But that's not super important.

2020-04-15 10:15 UTC, schTi approved these changes
I am still not a fan of the idea to move the metric title to the left, but it is okay for me now. Nice design upgrade in general! :fire:

2020-04-15 10:28 UTC, MaxSchneider1337 commented on hyrisecockpit/frontend/src/components/charts/Linechart.vue
> +      fill: "tonexty",
@Bouncner I wrote an extra issue for that. I tried to implement a simple responsive design, but it seems to be a bit more complex.

2020-04-15 10:29 UTC, merged