F/489 change distinctness of databases on comparison page
hyrise/Cockpit pull request #523
Opened 2020-04-15 17:04 UTC by monasobh

# Resolves #489 

**Does your pull request solve a problem? Please describe:**  
Implemented a colored header and took out the database system panel. 

**Affected Component(s):**  
`Frontend`

**Additional context:**  
Add any other context or screenshots about the pull request here.

2020-05-04 08:56 UTC, monasobh commented
@Bensk1 @Bouncner what do you think about the design? Could you please give me some feedback.

2020-05-04 09:00 UTC, Bensk1 commented
I like it, especially 1+4 and 3. Since this was Martin's idea, he should have the final `go` here.

2020-05-04 11:12 UTC, Bouncner commented
Looking good. A few small remarks:
 * I wouldn't put the description (host, capacity) below the actual value
 * I wouldn't put the units in bold, only the database name
 * Why does `database-1` and `Markets` differ?
 * What happens when we scroll? I am not a big fan of floats, so I think the "database bubble" would be helpful in any chart as long as we don't need the space (which is the case right now).
 * Can we somehow connect the "titlebox" with the vertical lines besides the plots?
 * I think half the width of the vertical lines is still fine.

When we settled on these remarks, we should have a little discussion round with all team members.

2020-05-04 17:11 UTC, monasobh commented
Please checkout the changes I made and let me know, what you think.

2020-05-05 06:50 UTC, Bouncner commented
If the font needs to be bold in order to be readable, we have either too dark background or we need to switch to white for certain colors.

Here is an algorithm that checks for the perceived contrast. This way, we could switch to white whenever necessary. But I am not sure if we want a database with white text on the left and another one with black text next to it.
Any ideas here?

Besides that, I like the PR. Maybe a bit more white space around the databases.

2020-05-07 11:49 UTC, monasobh commented
Here is an algorithm that checks for the perceived contrast. This way, we could switch to white whenever necessary. But I am not sure if we want a database with white text on the left and another one with black text next to it.
> Any ideas here?
I think white is the only option here. Couldn't find another color that is readable on all database colors. What do you think (new photo above)?

2020-05-07 12:33 UTC, Bouncner commented
Argh, I did not paste the link: https://stackoverflow.com/a/3943023/1147726 (and the linked duplicate issue).

The white wouldn't work for the light blue in the first pictures, wouldn't it? It this light blue gone?
Can you show the white text for all the possible colours?

2020-05-07 12:58 UTC, monasobh commented
> Argh, I did not paste the link: https://stackoverflow.com/a/3943023/1147726 (and the linked duplicate issue).
> 
> The white wouldn't work for the light blue in the first pictures, wouldn't it? It this light blue gone?
> Can you show the white text for all the possible colours?

Yes, the light blue is gone and replace by a stronger one. See above for all databases.

2020-05-11 12:03 UTC, schTi requested changes

2020-05-11 12:03 UTC, schTi commented on hyrisecockpit/frontend/src/components/container/MetricTile.vue
> +    :id="`${tileDatabase}-${metric}-tile`"
please move the id to the top

2020-05-11 12:03 UTC, schTi commented on hyrisecockpit/frontend/src/components/container/MetricTile.vue
> +import { Color } from "plotly.js";
this import isnt used anywhere

2020-05-11 12:03 UTC, schTi commented on hyrisecockpit/frontend/src/components/container/MetricTile.vue
> +#comparison-page .card {
Why do you need this class only on comparison page? Couldnt we have an equal design on the overview page?

2020-05-11 12:03 UTC, schTi commented on hyrisecockpit/frontend/src/components/container/MetricsComparisonTable.vue
> +import DatabaseSystemDetails from "../../components/details/DatabaseSystemDetails.vue";
unnecessary import here

2020-05-11 12:03 UTC, schTi commented on hyrisecockpit/frontend/src/components/details/DatabaseSystemDetails.vue
> +  margin-left: 6px;
the db system details are only shown on comparison and on overview page, so imo it is not necessary to scope those css classes here

2020-05-11 14:30 UTC, monasobh commented on hyrisecockpit/frontend/src/components/container/MetricTile.vue
> +#comparison-page .card {
Unfortunately not. The V-card on the comparison page can't be round on all corners, otherwise the vertical lines from the databases won't align right.

2020-05-11 14:31 UTC, monasobh commented on hyrisecockpit/frontend/src/components/details/DatabaseSystemDetails.vue
> +  margin-left: 6px;
If I don't use the #, all the v-cards we use e.g. Plugins will change..

2020-05-11 15:58 UTC, schTi commented on hyrisecockpit/frontend/src/components/container/MetricTile.vue
> +#comparison-page .card {
you can make the css scoped, just use `<style scoped>` instead of `<style>`

2020-05-11 15:58 UTC, schTi commented on hyrisecockpit/frontend/src/components/details/DatabaseSystemDetails.vue
> +  margin-left: 6px;
you can make the css scoped, just use <style scoped> instead of <style>

2020-05-11 15:58 UTC, schTi commented on hyrisecockpit/frontend/src/components/container/MetricTile.vue
> +#comparison-page .card {
nvm wrong comment section

2020-05-13 11:23 UTC, schTi approved these changes
Thanks for adding requested changes. Feel free to merge!

2020-05-13 13:11 UTC, merged