F/512-improve-ux-on-workload-generation
hyrise/Cockpit pull request #531
Opened 2020-04-16 12:22 UTC by kathwill

# Resolves #512 

**Does your pull request solve a problem? Please describe:**  
It is not always visible why you can not load or start a workload. 

**Does your pull request add a feature? Please describe:**  
There are now more warnings to inform the user and all user input on the workload generation dialog is disabled when no database is added, an instance is blocked or a workload is loaded.

**Affected Component(s):**  
`Frontend`

2020-04-20 10:01 UTC, Bouncner commented
What needs to happen that a database is "blocked"?

2020-04-20 12:25 UTC, kathwill commented
> What needs to happen that a database is "blocked"?

It is possible that a database is blocked when loading or removing data and when starting or stopping a workload. So now it is visible why certain buttons are disabled and which of the instances is still blocked. 
Do you think "blocked" is the wrong word for that?

2020-04-20 18:20 UTC, Bouncner commented
No, I think “blocked” is ok. Just wasn’t sure what it means.

Would it be possible to know why it is blocked? (e.g. “blocked due to data loading”)

2020-04-22 08:15 UTC, schTi requested changes

2020-04-22 08:15 UTC, schTi commented on hyrisecockpit/frontend/src/components/alerts/StatusWarning.vue
> +        :color="useDatabaseService().getDatabaseColor(database)"
It is a bit overkill to import the big database service here to just get the color. You can access those colors via the database controller directly, because they are stored together with the databases itself. You can have a look at the `DatabaseSystemDetails.vue`.

2020-04-22 08:15 UTC, schTi commented on hyrisecockpit/frontend/src/components/workload/WorkloadGeneration.vue
> +                  buttons.start.loading || !isLoaded(workload) || isDisabled()
Currently the tests are failing, because the buttons are not getting disabled, when there is no database. Thats because the `isDisabled` function here will only be called when mounting the component. To get notified, when there are changes, you have to use a computed property instead.

2020-04-22 08:15 UTC, schTi commented on hyrisecockpit/frontend/src/meta/events.ts
> +    eventBus.$emit("DATABASE_STATUS", database, blocked, active);
can you please rename this to `DATABASE_STATUS_CHANGED`? This would be more descriptive.

2020-04-22 08:15 UTC, schTi commented on hyrisecockpit/frontend/src/meta/events.ts
> +    eventBus.$emit("NO_DATABASE");
Same here. Maybe `NO_DATABASE_ADDED` would be better, to distinguish between added and selected.

2020-04-22 08:15 UTC, schTi commented on hyrisecockpit/frontend/src/controller/databaseController.ts
> +  function getDatabaseStatusInformation(): DatabaseStatus {
When I said, we can store those status information directly with the other database information, I really meant this. Why dont you just add `blocked` and `active` as additional properties to the database data inside the getDatabaseInformation- function. Imo you can initialize those values with `false`. Because the `status` endpoint will be called every second anyway.

2020-04-22 08:15 UTC, schTi commented on hyrisecockpit/frontend/src/controller/databaseController.ts
> +    "DATABASE_STATUS",
When you apply the changes of my other comment, then you can get rid of many of these lines. It should be something like: `const database = databases.value.find(element => element.id === database)` and then just adapt the entries `database.active` and `database.blocked` accordingly to the new values.

2020-04-22 08:15 UTC, schTi commented on hyrisecockpit/frontend/src/controller/databaseController.ts
> +  eventBus.$on("NO_DATABASE", () => {
The database controller stores all running databases. So he already knows, if there isnt any database.

2020-04-22 10:48 UTC, MaxSchneider1337 commented on hyrisecockpit/frontend/src/components/alerts/StatusWarning.vue
> +    const noDatabase = ref<boolean>(false);
could you please rename `noDatabase` to something more descriptive like `noDatabaseAvailable`. It is kind of hard to now if this is a boolean.

2020-04-22 10:48 UTC, MaxSchneider1337 commented on hyrisecockpit/frontend/src/components/alerts/StatusWarning.vue
> +    const noDatabase = ref<boolean>(false);
just read @schTi s comments and he suggested `selected` and `selected`. I don't mind the actual naming, but it should be more descriptive.

2020-04-22 16:26 UTC, schTi requested changes

2020-04-22 16:26 UTC, schTi commented on hyrisecockpit/frontend/src/components/alerts/StatusWarning.vue
> +          v-if="database.blocked"
just move the v-if directive to the top please to improve readability.

2020-04-22 16:26 UTC, schTi commented on hyrisecockpit/frontend/src/components/workload/WorkloadGeneration.vue
> +                  !isLoaded(workload) || isDisabled() || !databases.length
Can you tell me why you did not make the `isDisabled` a computed property?

2020-04-29 08:50 UTC, schTi requested changes
I really like the changes you made. The template is more readable now. But Im still having issues with the script part of the workload generation component. The setup functions is way to big. Its hard to see whats going on there, and what belongs to each other. Thats exactly what we want to prevent by using vue composition api. To increase the code organisation, I would suggest to split all related logic into an own function. For example: `useWorkloadActions` should contain everything needed for handling workload related stuff (starting, stopping, ..). These functions should be placed outside the setup function and they should have an own data interface. The setup function should then just return these functions. If you have any questions about that, just hit me up.

2020-04-29 08:50 UTC, schTi commented on hyrisecockpit/frontend/src/components/workload/WorkloadActions.vue
> +    function startingWorkload(): void {
You dont need those functions to just emit an event. You can directly do this in the template. For example: `@click="$emit('start')"`. You can do this everywhere when there is no other logic.

2020-04-29 08:50 UTC, schTi commented on hyrisecockpit/frontend/src/components/workload/WorkloadGeneration.vue
> +          :selected-metrics="['']"
why not pass an empty array here?

2020-04-29 08:50 UTC, schTi commented on hyrisecockpit/frontend/src/components/workload/WorkloadSelector.vue
> +      default: null,
you should always set a good default value. When you set null here, there will be an error, when no workload data has been passed. An empty object would be  the better choice for sure. For boolean values you should always take `true` or `false` as default. So you just need to pass a value in the other case.

2020-04-29 08:50 UTC, schTi commented on hyrisecockpit/frontend/src/components/workload/WorkloadGeneration.vue
> +              @change="handleWorkloadChange($event)"
```suggestion
              @change="handleWorkloadChange"
```
Thats exactly the same, but prettier :smile:

2020-04-29 08:59 UTC, kathwill commented on hyrisecockpit/frontend/src/components/workload/WorkloadGeneration.vue
> +          :selected-metrics="['']"
Then the warning will always be shown because there is no metric

2020-04-29 09:00 UTC, kathwill commented on hyrisecockpit/frontend/src/components/workload/WorkloadActions.vue
> +    function startingWorkload(): void {
Thanks!

2020-04-29 09:00 UTC, kathwill commented on hyrisecockpit/frontend/src/components/workload/WorkloadGeneration.vue
> +              @change="handleWorkloadChange($event)"
Thanks!

2020-04-29 09:24 UTC, schTi commented on hyrisecockpit/frontend/src/components/workload/WorkloadGeneration.vue
> +          :selected-metrics="['']"
Ah, I see.

2020-04-29 10:32 UTC, kathwill commented on hyrisecockpit/frontend/src/components/workload/WorkloadGeneration.vue
> +          :selected-metrics="['']"
Do you have a better way of doing that or should I just leave it as it is?

2020-04-29 10:54 UTC, schTi commented on hyrisecockpit/frontend/src/components/workload/WorkloadGeneration.vue
> +          :selected-metrics="['']"
Its okay for me

2020-04-29 10:58 UTC, schTi requested changes

2020-04-29 10:58 UTC, schTi commented on hyrisecockpit/frontend/src/types/workloads.ts
> +export interface WorkloadAction {
you can move this interface to the workload generation as well, because we dont need this anywhere else yet

2020-04-29 10:58 UTC, schTi commented on hyrisecockpit/frontend/src/components/workload/WorkloadGeneration.vue
> +  setup(props: {}, context: SetupContext): WorkloadAction {
thats not what I expected. You just moved all the stuff to an additional function. What I meant was splitting it in different functions. E.g. one function handles all frequency related stuff, the other one handles all loading stuff, ... . With your solution we still have the same readability issues.
Or do you think it is not possible to split this like I suggested?

2020-04-29 11:51 UTC, kathwill commented on hyrisecockpit/frontend/src/components/workload/WorkloadGeneration.vue
> +  setup(props: {}, context: SetupContext): WorkloadAction {
It's not possible to split workload and frequency, but workload-data is possible. So I will do that now

2020-04-29 15:41 UTC, Bouncner commented
Can you change the title to "Workload Settings" which is consistent with the menu?

2020-04-29 16:55 UTC, kathwill commented
> Can you change the title to "Workload Settings" which is consistent with the menu?

Yes

2020-04-30 09:02 UTC, schTi reviewed
Thanks for the great work, just one question.

2020-04-30 09:02 UTC, schTi commented on hyrisecockpit/frontend/src/controller/databaseController.ts
> +      if (databasesUpdated.value) {
Why do you need this?

2020-04-30 09:03 UTC, schTi commented on hyrisecockpit/frontend/src/controller/databaseController.ts
> +      if (databasesUpdated.value) {
Okay nvm, I got it :smile:

2020-04-30 09:03 UTC, schTi approved these changes

2020-04-30 09:04 UTC, kathwill commented on hyrisecockpit/frontend/src/controller/databaseController.ts
> +      if (databasesUpdated.value) {
In the setup there was sometimes an error because getDatabaseById(databaseId) was not defined yet

2020-04-30 09:17 UTC, merged