f/555 historic data range
hyrise/Cockpit pull request #557
Opened 2020-04-23 14:21 UTC by MaxSchneider1337

# Resolves #555

**Does your pull request add a feature? Please describe:**  
change requested historic data range 

**Affected Component(s):**  
Frontend

**Additional context:**  
Add any other context or screenshots about the pull request here.

2020-04-23 14:22 UTC, MaxSchneider1337 commented on hyrisecockpit/frontend/src/services/metricService.ts
> +      // if (dataCopy.length > 29) {
@schTi any ideas how to access the metricController data her to get the historic data range?

2020-04-23 14:22 UTC, MaxSchneider1337 commented
overview timestamps style bugs when range is to hight

2020-04-23 14:56 UTC, schTi commented on hyrisecockpit/frontend/src/services/metricService.ts
> +      // if (dataCopy.length > 29) {
Just pass it as additional parameter inside the start function?

2020-04-27 08:08 UTC, schTi requested changes
Good stuff, just one thing

2020-04-27 08:08 UTC, schTi commented on hyrisecockpit/frontend/src/components/charts/Linechart.vue
> +        getLayout(props.maxValue, getHistoricRangeMinutes() * 60),
You always need to multiply with 60, so why not wrap this in a function?

2020-04-27 08:30 UTC, MaxSchneider1337 commented on hyrisecockpit/frontend/src/components/charts/Linechart.vue
> +        getLayout(props.maxValue, getHistoricRangeMinutes() * 60),
good point. this even stood on my list, but I forgot it.

2020-04-27 10:14 UTC, schTi requested changes

2020-04-27 10:14 UTC, schTi commented on hyrisecockpit/frontend/src/controller/metricController.ts
> +  function gethistoricRangeSeconds(): number {
should be getHistoricRangeSeconds

2020-04-27 10:50 UTC, schTi approved these changes
Good job

2020-04-27 11:49 UTC, merged