F/520 responsive design
hyrise/Cockpit pull request #582
Opened 2020-05-04 11:20 UTC by MaxSchneider1337

# Resolves #520

**Does your pull request solve a problem? Please describe:**  
adds responsiveness to comparison screen.

**Affected Component(s):**  
Frontend

2020-05-06 09:15 UTC, schTi requested changes

2020-05-06 09:15 UTC, schTi commented on hyrisecockpit/frontend/src/components/container/MetricTile.vue
> +  isThin: boolean;
I dont know, but isThin doesnt seem to be good naming here. Maybe you could find a more functional name here

2020-05-06 09:15 UTC, schTi commented on hyrisecockpit/frontend/src/components/container/MetricTile.vue
> +import { eventBus } from "@/plugins/eventBus";
this import isnt used anywhere

2020-05-06 09:15 UTC, schTi commented on hyrisecockpit/frontend/src/components/container/MetricsComparisonTable.vue
> +  needsThinTiles: Readonly<Ref<boolean>>;
also naming here

2020-05-25 07:55 UTC, MaxSchneider1337 commented
closed due to old dev version

2020-05-25 07:55 UTC, closed without merging