F/539-add-equalizer-to-workload-generation
hyrise/Cockpit pull request #604
Opened 2020-05-07 15:14 UTC by kathwill

# Resolves #539 

**Does your pull request add a feature? Please describe:**  
By adding the equalizer it is now possible to change the weights for the queries of a workload.

**Affected Component(s):**  
`Frontend`

**Additional context:**
<img width="822" alt="Screenshot 2020-05-07 at 17 10 47" src="https://user-images.githubusercontent.com/49514526/81311675-fdb88580-9085-11ea-9505-a1304480cb3b.png">
<img width="823" alt="Screenshot 2020-05-07 at 17 11 38" src="https://user-images.githubusercontent.com/49514526/81311689-001adf80-9086-11ea-8443-ed25e2082b5f.png">

2020-05-08 14:49 UTC, schTi requested changes

2020-05-08 14:49 UTC, schTi commented on hyrisecockpit/frontend/src/components/workload/WeightsHandler.vue
> +<template>
Thats the equalizer component, so why not call it equalizer?

2020-05-08 14:49 UTC, schTi commented on hyrisecockpit/frontend/src/components/workload/WeightsHandler.vue
> +        v-for="(weight, key) in weights"
You should change the order of `v-model` and `v-for`. Then you may notice that `weights[key]` is basically `weight`

2020-05-08 14:49 UTC, schTi commented on hyrisecockpit/frontend/src/components/workload/WeightsHandler.vue
> +        max="200"
Is the max value always 200? Can you tell me what unit those weights are measured in? Maybe this would be a useful information for the user, too

2020-05-08 14:49 UTC, schTi commented on hyrisecockpit/frontend/src/components/workload/WorkloadGeneration.vue
> +                      </v-tooltip>
In my opinion its enough to switch to the equalizer page via tab header. So just get rid of this button.

2020-05-08 14:49 UTC, schTi commented on hyrisecockpit/frontend/src/components/workload/WorkloadGeneration.vue
> +          <v-card flat>
Why do you need this card?

2020-05-08 14:49 UTC, schTi commented on hyrisecockpit/frontend/src/components/workload/WorkloadGeneration.vue
> +  tab: number;
Should be `Ref<number>`

2020-05-08 14:49 UTC, schTi commented on hyrisecockpit/frontend/src/components/workload/WorkloadGeneration.vue
> +    const tab: number = 0;
This explicit `number` declaration is unnecessary

2020-05-10 12:06 UTC, MaxSchneider1337 commented on hyrisecockpit/frontend/src/components/workload/WeightsHandler.vue
> +        v-for="(weight, key) in weights"
this does not work: `'v-model' directives cannot update the iteration variable 'weight' itself.`

2020-05-10 12:36 UTC, schTi commented on hyrisecockpit/frontend/src/components/workload/WeightsHandler.vue
> +        v-for="(weight, key) in weights"
Yes nvm you're absolutely right. But the order can still be changed

2020-05-10 12:44 UTC, kathwill commented on hyrisecockpit/frontend/src/components/workload/WorkloadGeneration.vue
> +          <v-card flat>
Otherwise the text color changes, but alternatively I can also add the text color to every text.

2020-05-10 14:06 UTC, kathwill commented on hyrisecockpit/frontend/src/components/workload/WeightsHandler.vue
> +        max="200"
There is no real max value. If query 1 has the weight 200, query 2 the weight 100 and there are only these two queries in the workload, 2/3 of all queries are query 1 and 1/3 is query 2. We could think of a relative representation of the weights too.

2020-05-10 17:05 UTC, Bouncner commented
> There is no real max value. If query 1 has the weight 200, query 2 the weight 100 and there are only these two queries in the workload, 2/3 of all queries are query 1 and 1/3 is query 2. We could think of a relative representation of the weights too.

I was discussing this with Jan lately. We’ll come back to you.
Do you know if a non-linear increase is possible?

2020-05-11 09:30 UTC, kathwill commented
> Do you know if a non-linear increase is possible?
I believe that should be possible.

2020-05-11 13:26 UTC, MaxSchneider1337 commented
![image](https://user-images.githubusercontent.com/38442947/81566880-c99dd700-939b-11ea-9f91-d57dc5d813a4.png)

2020-05-11 18:06 UTC, Bouncner commented
Since this needs to play well with the backend: what is the status there? How would the absolute query counts (as shown in this draft) be used?

2020-05-12 10:08 UTC, kathwill commented
> Since this needs to play well with the backend: what is the status there? How would the absolute query counts (as shown in this draft) be used?

Like I said before, so: 
>If query 1 has the weight 200, query 2 the weight 100 and there are only these two queries in the workload, 2/3 of all queries are query 1 and 1/3 is query 2.

So it is always: (weight of query) / (sum of the weights of all queries of this workload)

2020-05-12 14:16 UTC, Bouncner commented
If it is a weight, please use 1.0 as the default weight.

But that still doesn't answer how the backend handles these weights.

2020-05-12 16:07 UTC, fabianhe commented
> But that still doesn't answer how the backend handles these weights.

We're using [`random.choices`](https://docs.python.org/3/library/random.html#random.choices) from the Python Standard library [here](https://github.com/hyrise/Cockpit/blob/13dc940d1b4fe8a5a5b4012fda33cf6602aba548/hyrisecockpit/workload_generator/workload.py#L72).
Weights are expected to be `int`, but we can use `float` instead. Initially, all weights are `100`.

The probability of a generating a query is its weight divided by the sum of all weights:
> [If a weights sequence is specified, selections are made according to the relative weights.](https://docs.python.org/3/library/random.html#random.choices)

2020-05-14 06:56 UTC, schTi requested changes

2020-05-14 06:56 UTC, schTi commented on hyrisecockpit/frontend/src/components/workload/Equalizer.vue
> +            :value="weight.weight"
`:value:` property can be removed here, because this is exactly what `v-model` does

2020-05-14 06:56 UTC, schTi commented on hyrisecockpit/frontend/src/components/workload/Equalizer.vue
> +  weights: Ref<{ name: string; weight: number }[]>;
You can declare a new type here to reuse this declaration. Something like `type Weight = { name: ... }`

2020-05-14 06:56 UTC, schTi commented on hyrisecockpit/frontend/src/components/workload/Equalizer.vue
> +          });
In my optionion you could use `map`  here instead of `forEach`

2020-05-14 06:56 UTC, schTi commented on hyrisecockpit/frontend/src/components/workload/WorkloadGeneration.vue
> +      updatingWorkload().then((response: any) => {
Can you tell me why you need to call the update workload function here ?

2020-05-14 06:56 UTC, schTi commented on hyrisecockpit/frontend/src/components/workload/WorkloadGeneration.vue
> +      updatingWorkload().then((response: any) => {
Is it because you would not get the weights otherwise ?

2020-05-14 06:56 UTC, schTi commented on hyrisecockpit/frontend/src/components/workload/WorkloadGeneration.vue
> +  let weights = ref<Record<string, number>>({});
`ref` variables should always be `const`, because you just change the `value` property, but not the declaration itself.

2020-05-14 10:18 UTC, kathwill commented on hyrisecockpit/frontend/src/components/workload/WorkloadGeneration.vue
> +      updatingWorkload().then((response: any) => {
Yes, that's right!

2020-05-20 07:20 UTC, schTi requested changes
Looks good so far. Just some minor improvement suggestions.

2020-05-20 07:20 UTC, schTi commented on hyrisecockpit/frontend/src/components/workload/Equalizer.vue
> +    const b = Math.pow(99, 1 / 50);
Can you please add some commentary here? Looks like there are some magic numbers and I dont understand where they come from.

2020-05-20 07:20 UTC, schTi commented on hyrisecockpit/frontend/src/components/workload/Equalizer.vue
> +      context.emit("change", name, value);
That is basically the same function except the conversion part. You could merge this to one single function accepting the conversion function as parameter.

2020-05-20 07:20 UTC, schTi commented on hyrisecockpit/frontend/src/components/workload/Equalizer.vue
> +    }
Can you tell me in a few words, what you need to convert here? Just for my understanding :smile:

2020-05-25 13:00 UTC, kathwill commented on hyrisecockpit/frontend/src/components/workload/Equalizer.vue
> +    }
A non linear increase of the weight values was required, but the v-slider only offers linear increases. So I created an exponential function that converts slider values to our weight values and vice versa. By changing a and b we could still change the value range.

2020-05-25 13:13 UTC, Bouncner commented
18 days old. What's the status?

2020-05-25 14:02 UTC, schTi requested changes
just one minor thing

2020-05-25 14:02 UTC, schTi commented on hyrisecockpit/frontend/src/components/workload/Equalizer.vue
> +      context.emit("change", name, weight.value);
In general its cool to use `?` shortcut for assignments, but it can be really misleading using this with expressions. Maybe good old if and else is more suitable here.

2020-05-25 14:02 UTC, schTi commented on hyrisecockpit/frontend/src/components/workload/Equalizer.vue
> +    f(0) = 0, f(50) = 100, f(100) =  10000 --> b = 99^(1/50), a = 50/49 */
thanks for the comment. We should always be aware of adding comments to critical functions/ logic. So it would be nice if you can add some comments to all logic, which you thinks needs some further explanation, in the future.

2020-05-26 09:42 UTC, fabianhe commented
> If it is a weight, please use 1.0 as the default weight.

Weights are now `float` with `1.0` as default in the backend.

2020-05-26 12:19 UTC, schTi approved these changes
Really good work. Merge if you are happy :fire:

2020-05-26 13:35 UTC, merged

2020-05-26 13:38 UTC, Bouncner commented
Niiiice!

Looking forward seeing it live in action. 🙂