F/597-start-multiple-workloads
hyrise/Cockpit pull request #627
Opened 2020-05-14 10:17 UTC by kathwill

# Resolves #597 

**Does your pull request add a feature? Please describe:**  
It is now possible to start multiple workloads and start/stop of the workload and of the workers is separated.

**Affected Component(s):**  
`Frontend`

**Additional context:**  
<img width="819" alt="MultipleWorkloads1" src="https://user-images.githubusercontent.com/49514526/81922746-d5c4a700-95dc-11ea-875b-cf9d4d945519.png">

2020-06-08 14:14 UTC, schTi requested changes
Looks great, just some really small issues

2020-06-08 14:14 UTC, schTi commented on hyrisecockpit/frontend/src/components/workload/FrequencyHandler.vue
> +          v-model="frequencies[index]"
please change the order of those statements

2020-06-08 14:14 UTC, schTi commented on hyrisecockpit/frontend/src/components/workload/FrequencyHandler.vue
> +          v-model="frequencies[index]"
same here

2020-06-08 14:14 UTC, schTi commented on hyrisecockpit/frontend/src/components/workload/FrequencyHandler.vue
> +      default: [],
Thats not gonna work, for complex types like objects or arrays you need to use an initializer. Basically this means you need to change the default value to a function like this: `() => []`

2020-06-08 14:14 UTC, schTi commented on hyrisecockpit/frontend/src/components/workload/WorkloadGeneration.vue
> +    const workloadAction = useWorkloadAction(context);
In my opinion there are multiple different actions, so it should be named `workloadActions` and `useWorkloadActions`

2020-06-08 14:14 UTC, schTi commented on hyrisecockpit/frontend/src/components/workload/WorkloadGeneration.vue
> +  function initialiseWorkloadSelector(workloads: any): void {
I dont know but `initialise` looks weird to me, I am only familiar with `initialize`

2020-06-08 14:14 UTC, schTi commented on hyrisecockpit/frontend/src/components/workload/WorkloadGeneration.vue
> +      //load workload data
```suggestion
      // load workload data
```

2020-06-08 14:31 UTC, kathwill commented on hyrisecockpit/frontend/src/components/workload/WorkloadGeneration.vue
> +  function initialiseWorkloadSelector(workloads: any): void {
It's British English, but I will change it.

2020-06-08 14:32 UTC, kathwill commented on hyrisecockpit/frontend/src/components/workload/FrequencyHandler.vue
> +      default: [],
I think it's only a naming issue then. I wanted to make clear that the prop sets the initial frequencies (which are initialised in the WorkloadGeneration) and there are then changed by using the sliders or text fields of the FrequencyHandler

2020-06-09 06:26 UTC, schTi approved these changes
Thanks for the small fixes. If you can ensure that everything is working, feel free to merge. Good job

2020-06-10 09:44 UTC, merged