Docker/ Build non-natively for broader CPU support
hyrise/Cockpit pull request #644
Opened 2020-05-22 12:32 UTC by cH3n7i

**Does your pull request solve a problem? Please describe:**  
The given process currently builds for the building architecture. This leads to `SIGILL` and other failures if we run an image build on new hardware in old setups. 

**Does your pull request add a feature? Please describe:**  
Additionally to the native version, we can now build with support up to Core2 CPUs. This should cover the needs generously.

**Affected Component(s):**  
`Hyrise`

2020-05-22 18:32 UTC, Bouncner commented
I know nothing is clean with Docker, but copy pasting looks quite aweful. Can’t we pass a parameter and have default arguments.

2020-05-26 11:43 UTC, heseding approved these changes

2020-05-26 12:46 UTC, Bouncner requested changes

2020-05-26 12:46 UTC, Bouncner commented on hyrise/Dockerfile_core2
> +    && make CompressionPlugin ClusteringPlugin IndexSelectionPlugin \
Still two files?

2020-05-26 15:27 UTC, cH3n7i commented on hyrise/Dockerfile_core2
> +    && make CompressionPlugin ClusteringPlugin IndexSelectionPlugin \
File deleted now

2020-05-26 16:59 UTC, merged