Refactor Plugin Log
hyrise/Cockpit pull request #656
Opened 2020-05-27 12:57 UTC by fabianhe

# Resolves #605, Resolves #610

**Does your pull request solve a problem? Please describe:**  
- Plugin logs are huge when not filtered by level.
- The `/plugin_log` route is not adapted to the new structure
- The `/plugin_log` route is not tested

**Does your pull request add a feature? Please describe:**  
- [ ] Implements a filter for log levels
- [ ] Ports the `GET` `/plugin_log` route to `GET` `/plugin/log`
- [ ] Tests the new `GET` `/plugin/log` route

**Affected Component(s):**  
`CockpitBackend`

2020-07-17 13:21 UTC, PeterTsayun approved these changes

2020-07-24 09:41 UTC, caterinamandel98 approved these changes

2020-07-28 10:39 UTC, PeterTsayun requested changes
I've just tested this PR and got some error messages when requesting `/control/plugin/log`.

Steps to reproduce:

1. Start the cockpit
2. Add database
3. Request GET `/control/plugin/log`

Following error message occurs:
```
  File "/home/Petr.Tsayun/Cockpit/hyrisecockpit/api/app/plugin/service.py", line 114, in get_all_plugin_logs
    return [
  File "/home/Petr.Tsayun/Cockpit/hyrisecockpit/api/app/plugin/service.py", line 125, in <listcomp>
    cls._query_storage_connection(query, database, bind_params)[
TypeError: 'NoneType' object is not subscriptable
```

2020-07-31 15:03 UTC, PeterTsayun approved these changes

2020-08-07 05:15 UTC, merged