Unify close buttons and design
hyrise/Cockpit pull request #683
Opened 2020-07-14 14:58 UTC by monasobh

# Resolves #667 

**Does your pull request solve a problem? Please describe:**  
We now have a similar close button and similar design on the different windows/dialogues. 

**Does your pull request add a feature? Please describe:**  
See pictures in Isssue #667 

**Affected Component(s):**  
`Settings`, `UI`,

2020-07-14 15:58 UTC, schTi requested changes

2020-07-14 15:58 UTC, schTi commented on hyrisecockpit/frontend/src/components/selection/DatabaseSelection.vue
> +}
Its no good style to directly overwrite vuetify classes. As you have access to all of those elements, just add a simple custom class and use it for subtitle, title, and text of the card

2020-07-14 15:58 UTC, schTi commented on hyrisecockpit/frontend/src/components/selection/MetricSelection.vue
> +</style>
same here

2020-07-14 15:58 UTC, schTi commented on hyrisecockpit/frontend/src/components/selection/SelectionList.vue
> +  text-transform: none !important;
same for v-tab here, you could just use a custom class

2020-07-14 15:58 UTC, schTi commented on hyrisecockpit/frontend/src/components/selection/SelectionList.vue
> +  text-transform: none !important;
whats the reason for this?

2020-07-14 15:58 UTC, schTi commented on hyrisecockpit/frontend/src/components/selection/SelectionList.vue
> +    },
Looks like React-style 😄 . In Vue you would normally emit a `close`-event to the parent, and the parent would call the `onClose`- function on his own. So you dont need to pass the closing function to the child

2020-07-14 16:19 UTC, monasobh commented on hyrisecockpit/frontend/src/components/selection/SelectionList.vue
> +    },
Ok. That's also how the Plugins close button works.. Maybe we should find a consistent solution 👍

2020-07-14 16:27 UTC, monasobh commented on hyrisecockpit/frontend/src/components/selection/SelectionList.vue
> +  text-transform: none !important;
it allows the text in a button to be in small letters not caps lock

2020-07-14 16:48 UTC, schTi commented on hyrisecockpit/frontend/src/components/selection/SelectionList.vue
> +    },
Yes, because Max implemented this :D. Consistent would be to use events only

2020-07-15 07:53 UTC, schTi reviewed
Please resolve those conflicts before you continue, this will apply some changes to the test code as well

2020-07-15 14:12 UTC, schTi commented
You removed the ID of the add database button. To fix the tests, just add `data-id="add-database-button"` to the new button

2020-07-17 15:17 UTC, schTi approved these changes
Great work!

2020-07-18 10:21 UTC, monasobh commented
> Great work!

Did some more changes. Please re-review. Thanks!

2020-07-18 11:07 UTC, schTi approved these changes

2020-07-18 14:14 UTC, merged