F/690-improve-equalizer
hyrise/Cockpit pull request #697
Opened 2020-07-15 11:16 UTC by kathwill

# Resolves #690

**Does your pull request solve a problem? Please describe:**  
The tab for the equalizer is not self descriptive. The pull request changes the name of the tab and adds explanations for the shown numbers.

**Affected Component(s):**  
`Frontend`

2020-07-17 10:16 UTC, kathwill commented
What do you think of this option? @Bensk1 @Bouncner

2020-07-17 14:56 UTC, Bensk1 commented
We are getting there!

- I am not a UI expert but what about putting the descriptions _query numbers_ and _query weights_ on the left side?
- Could we also rename _Query numbers_ to _Query ID_ and _Query Weights_ to _Query Weight_?
- Also, while we are on it. Do you think that a reset button (including functionality) is complicated?

2020-07-18 06:13 UTC, Bouncner commented
Is it possible to change the input fields style to make it more obvious that this is an editable field and not just text?

2020-07-27 11:30 UTC, kathwill commented
I renamed _Query numbers_ to _Query ID_ and _Query Weights_ to _Query Weight_ and added a reset button (as you can see in the pictures above).

> I am not a UI expert but what about putting the descriptions _query numbers_ and _query weights_ on the left side?

I decided to put it on the right side because I think if we put it on the left side it is too much information on that side because of the scale.

2020-07-28 06:26 UTC, Bensk1 commented
> I decided to put it on the right side because I think if we put it on the left side it is too much information on that side because of the scale. What do you think of this @Bensk1?

Perfect, I like that better.

2020-07-29 07:32 UTC, schTi requested changes

2020-07-29 07:32 UTC, schTi commented on hyrisecockpit/frontend/src/components/workload/QueryWeights.vue
> +              "
looks like this logic can be outsourced in an own function

2020-07-29 07:32 UTC, schTi commented on hyrisecockpit/frontend/src/components/workload/QueryWeights.vue
> +          weight.sliderValue = 50;
can you add a comment, why 50 is the base value?

2020-07-30 16:09 UTC, schTi approved these changes

2020-07-30 16:47 UTC, merged