F/688-change-dialog-for-adding-databases
hyrise/Cockpit pull request #700
Opened 2020-07-16 09:00 UTC by kathwill

# Resolves #688 

**Does your pull request solve a problem? Please describe:**  
The current dialog for adding databases confuses because of the "Show advanced"-option and too many input fields. This pull request will simplify the dialog.

**Affected Component(s):**  
`Frontend`

**Additional context:**  
Before:
<img width="603" alt="AddDatabaseDialog" src="https://user-images.githubusercontent.com/49514526/87651639-6f324580-c753-11ea-9510-570668667b5b.png">

After:
<img width="602" alt="ChangeDatabaseDialog" src="https://user-images.githubusercontent.com/49514526/87651216-0ba81800-c753-11ea-84a2-d59678fd494a.png">

2020-07-17 15:23 UTC, schTi reviewed
Can you add some type of form validation? So that it is not possible to click the save button, if not all inputs are filled?

2020-07-21 17:12 UTC, kathwill commented
> Can you add some type of form validation? So that it is not possible to click the save button, if not all inputs are filled?

I added form validation. All input fields must now be filled to click the save button.

2020-07-22 08:58 UTC, schTi requested changes
some minor things 😄

2020-07-22 08:58 UTC, schTi commented on hyrisecockpit/frontend/src/components/databases/AddDatabase.vue
> +            number_workers.length === 0
```suggestion
            !number_workers.length
```
this is equivalent

2020-07-22 08:58 UTC, schTi commented on hyrisecockpit/frontend/src/components/databases/AddDatabase.vue
> +import { useDatabaseService } from "../../services/databaseService";
please revert this

2020-07-22 08:58 UTC, schTi commented on hyrisecockpit/frontend/src/components/databases/AddDatabase.vue
> +          small
In my opinion the button is a bit too small, it could be much wider as I see it. And there could be some margin top, too. Its a bit overlapping, when number of workers input is empty

And why is it not color=primary? Because it is the primary action, isnt it?

2020-07-22 17:32 UTC, kathwill commented on hyrisecockpit/frontend/src/components/databases/AddDatabase.vue
> +            number_workers.length === 0
I know, but it didn't function like this. When I debugged it, I saw that the number_workers.length is not set in the beginning. That's why your suggested change leads to a warning at the beginning even though there are 8 workers. I believe it is because of the number type of the text field.

2020-07-22 17:37 UTC, kathwill commented on hyrisecockpit/frontend/src/components/databases/AddDatabase.vue
> +          small
I agree with the margin and the size of the button.
I chose the secondary color for the button and the primary color for the text because I like the fitting with the system bar.

2020-07-23 06:11 UTC, schTi commented on hyrisecockpit/frontend/src/components/databases/AddDatabase.vue
> +          small
Okay, I am cool with it

2020-07-23 06:15 UTC, schTi commented on hyrisecockpit/frontend/src/components/databases/AddDatabase.vue
> +            number_workers.length === 0
Okay

2020-07-23 06:16 UTC, schTi approved these changes

2020-07-23 10:39 UTC, merged