F/691 change navbar and comparison page design
hyrise/Cockpit pull request #702
Opened 2020-07-17 20:53 UTC by monasobh

# Resolves #691 

**Does your pull request solve a problem? Please describe:**  
This PR changes the design of the Navigation and the Comparison Page

**Does your pull request add a feature? Please describe:**  
See pictures in Issue #691 

**Affected Component(s):**  
`UI`, `Frontend`,

2020-07-18 08:34 UTC, Bouncner commented
I am absolutely no fan of custom fonts. Please at least add alternatives for Roboto etc.
Actually, I’d say there needs to be a very good reason before even just thinking about alternative fonts.

2020-07-18 08:50 UTC, monasobh commented
> I am absolutely no fan of custom fonts. Please at least add alternatives for Roboto etc.
> Actually, I’d say there needs to be a very good reason before even just thinking about alternative fonts.

I'm not sure what you mean. Please comment in the linked issue for more detailed feedback, this is a WIP PR. We use different size and style of Roboto everywhere. Check out https://vuetifyjs.com/en/styles/text-and-typography/#text-and-typography for more details.

2020-07-18 11:17 UTC, schTi requested changes

2020-07-18 11:17 UTC, schTi commented on hyrisecockpit/frontend/src/components/container/MetricTile.vue
> -    :style="getBorderColor(tileDatabase)"
You dont use the `getBorderColor` function anymore. So you can remove it

2020-07-18 11:17 UTC, schTi commented on hyrisecockpit/frontend/src/components/container/MetricsComparisonTable.vue
> +.v-card:not(.v-sheet--tile):not(.v-card--shaped) {
This is not a good practice. As I said earlier, it is more suitable to use a custom class and add this to every element, where you need this, as you have access to all elements. Overwriting internal vuetify classes is not cool, because:
- you dont know where this class will be applied to
- it increases coupling between vuetify internals and application code
- making stylesheets global would change the whole application design

2020-07-18 11:17 UTC, schTi commented on hyrisecockpit/frontend/src/components/metrics/Access.vue
> +            :items="tables"
```suggestion
            :items="selectionItems"
```

2020-07-18 11:17 UTC, schTi commented on hyrisecockpit/frontend/src/components/metrics/Access.vue
> +        v-model="selectedTable"
```suggestion
        v-model="selectedItem"
```

2020-07-18 11:17 UTC, schTi commented on hyrisecockpit/frontend/src/components/metrics/Access.vue
> +        :items="tables"
```suggestion
        :items="selectedItems"
```

2020-07-18 11:17 UTC, schTi commented on hyrisecockpit/frontend/src/components/metrics/Access.vue
> +.v-application .mt-n12 {
See comment above!

2020-07-18 11:17 UTC, schTi commented on hyrisecockpit/frontend/src/views/AppDrawer.vue
> +.v-application .mt-10 {
same here

2020-07-22 12:13 UTC, schTi requested changes

2020-07-22 12:13 UTC, schTi commented on hyrisecockpit/frontend/src/components/metrics/Access.vue
> +        :items="selectedItems"
```suggestion
         :items="selectionItems"
```
Sorry, I just made a typo in my last review, this is the correct value

2020-07-22 12:13 UTC, schTi commented on hyrisecockpit/frontend/src/views/AppDrawer.vue
> +        color="#02789D"
Can you add this color as vuetify variable to reuse it?

2020-07-22 12:13 UTC, schTi commented on hyrisecockpit/frontend/src/views/AppDrawer.vue
> +        <v-text class="caption ml-n11 mt-10 font-weight-regular-light"
`v-text` is not a vuetify component. Please use something that actually exists 😄

2020-07-22 12:13 UTC, schTi commented on hyrisecockpit/frontend/src/views/AppDrawer.vue
> +        <v-text class="caption ml-n15 mt-10 font-weight-regular-light"
same here

2020-07-22 12:13 UTC, schTi commented on hyrisecockpit/frontend/src/views/AppDrawer.vue
> +        <v-text class="caption ml-n9 mt-10 font-weight-regular-light"
again

2020-07-22 12:13 UTC, schTi commented on hyrisecockpit/frontend/src/views/AppDrawer.vue
> +        <v-text class="caption ml-n8 mt-10 font-weight-regular-light"
+1

2020-07-22 12:13 UTC, schTi commented on hyrisecockpit/frontend/src/views/AppDrawer.vue
> +            <v-text class="caption ml-n10 mt-10 font-weight-regular-light"
+1

2020-07-22 13:18 UTC, monasobh commented on hyrisecockpit/frontend/src/views/AppDrawer.vue
> +        <v-text class="caption ml-n11 mt-10 font-weight-regular-light"
wooops. got mixed up with v-title here. thanks!

2020-07-22 15:31 UTC, schTi requested changes

2020-07-22 15:31 UTC, schTi commented on hyrisecockpit/frontend/src/views/AppDrawer.vue
> +        <v-title class="caption ml-n9 mt-10 font-weight-regular-light"
As I see it `v-title` does not exist, as well 😄 . Just check your browser console, you should see some errors.

2020-07-22 16:07 UTC, monasobh commented on hyrisecockpit/frontend/src/views/AppDrawer.vue
> +        <v-title class="caption ml-n9 mt-10 font-weight-regular-light"
hahah! oh wow. I meant v-card-text. 😆

2020-07-23 06:10 UTC, schTi approved these changes
Good work

2020-07-23 08:25 UTC, merged