change query table to metric
hyrise/Cockpit pull request #713
Opened 2020-07-23 13:17 UTC by monasobh

# Resolves #703 

**Does your pull request solve a problem? Please describe:**  
This PR changes includes the query tables into the coloured database columns. 

**Does your pull request add a feature? Please describe:**  
Checkout photos #703 

**Affected Component(s):**  
`UI`, `Frontend`,

2020-07-26 18:47 UTC, schTi commented
I registered the query information as metric and moved those tables into the list container. This should be done now. Hit me up, when I missed something. Can you have a look a the design now? And maybe you could add the database details to the top of the page similar to the other views @monasobh

2020-07-27 09:30 UTC, schTi requested changes
Looks good

2020-07-27 09:30 UTC, schTi commented on hyrisecockpit/frontend/src/views/WorkloadMonitoring.vue
> +import DatabaseSystemDetails from "../components/details/DatabaseSystemDetails.vue";
```suggestion
import DatabaseSystemDetails from "@/components/details/DatabaseSystemDetails.vue";
```

This makes life easier, because it is a dynamic import from root directory

2020-07-27 09:57 UTC, schTi approved these changes
feel free to merge if you are happy

2020-07-28 15:50 UTC, schTi commented
Why did you remove the system details?

2020-07-28 16:03 UTC, monasobh commented
> Why did you remove the system details?

Because Jan said that this information is not necessary there.

2020-07-29 07:30 UTC, schTi requested changes

2020-07-29 07:30 UTC, schTi commented on hyrisecockpit/frontend/src/components/container/MetricsComparisonTable.vue
> +        <v-card-text class="temp white--text text-center mt-n3 mb-n2">
what is the temp class?

2020-07-29 07:30 UTC, schTi commented on hyrisecockpit/frontend/src/services/transformationService.ts
> +  return entry.query_information.map((query: any) => {
```suggestion
  return entry.detailed_query_information.map((query: any) => {
```
This was changed in a backend PR (see #722). It also needs to be adapted in the test code. I am going to do this. This comment is just a TODO for me

2020-07-29 07:30 UTC, schTi commented on hyrisecockpit/frontend/src/components/details/DatabaseSystemDetails.vue
> +#comparison-page .flex {
Is this really necessary? I dont like using css with ids which come out of nowwhere

2020-07-30 16:07 UTC, schTi approved these changes

2020-07-30 16:07 UTC, merged