F/693 add and improve tooltips
hyrise/Cockpit pull request #727
Opened 2020-07-30 09:37 UTC by monasobh

# Resolves #693 

**Does your pull request solve a problem? Please describe:**  
Removes unnecessary tooltips and adds useful tooltips.  

**Does your pull request add a feature? Please describe:**  
Checkout #693 for photos.

**Affected Component(s):**  
`Frontend`, `UI`

2020-07-30 17:46 UTC, schTi requested changes

2020-07-30 17:46 UTC, schTi commented on hyrisecockpit/frontend/src/components/selection/SelectionList.vue
> +              </v-btn>
please revert this, because this will be gone in PR #709 anyway

2020-07-30 18:44 UTC, monasobh commented on hyrisecockpit/frontend/src/components/selection/SelectionList.vue
> +              </v-btn>
done

2020-07-31 07:15 UTC, schTi approved these changes

2020-07-31 07:42 UTC, merged