F/726-rename-table-names-in-frontend
hyrise/Cockpit pull request #729
Opened 2020-07-30 10:04 UTC by kathwill

# Resolves #726 

**Does your pull request solve a problem? Please describe:**  
The shown table names in the heatmap and treemap of the comparison page are difficult to read.

**Does your pull request add a feature? Please describe:**  
By mapping the table names to selected labels the readability is improved.

**Affected Component(s):**  
`Frontend`

**Additional context:**  
<img width="507" alt="RenameTableNames1" src="https://user-images.githubusercontent.com/49514526/88910210-6c0f7d00-d25c-11ea-9d77-7b543dd7b198.png">
<img width="634" alt="RenameTableNames2" src="https://user-images.githubusercontent.com/49514526/88910217-6f0a6d80-d25c-11ea-9252-439155827311.png">
<img width="634" alt="RenameTableNames3" src="https://user-images.githubusercontent.com/49514526/88910220-6fa30400-d25c-11ea-9e1e-e090c1e4e650.png">

2020-07-30 14:14 UTC, schTi requested changes

2020-07-30 14:14 UTC, schTi commented on hyrisecockpit/frontend/src/meta/names.ts
> +}
Instead of using direct string concatenation, can you use template string? (see https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/template_strings)

2020-07-30 17:50 UTC, Bouncner commented on hyrisecockpit/frontend/src/meta/names.ts
> +  const words = table.split("_");
Do you have an example input here? I am worried that this could be a little bit to unspecific and might catch cases it shouldn’t.

2020-07-30 18:06 UTC, kathwill commented on hyrisecockpit/frontend/src/meta/names.ts
> +  const words = table.split("_");
lineitem_tpch_0_1

2020-07-30 19:40 UTC, Bouncner commented on hyrisecockpit/frontend/src/meta/names.ts
> +  const words = table.split("_");
Hmm, the Join order benchmark has a table called `comp_cast_type.csv`, almost reaching the threshold. To be more future proof, we could add a safeguard that expects `tpch`/`tpcds`/`job` in the string.

@Bensk1 : do you know any benchmark tables that might already screw this up?

2020-07-31 08:33 UTC, Bensk1 commented on hyrisecockpit/frontend/src/meta/names.ts
> +  const words = table.split("_");
No, I don't know anything right now but I agree that this could easily be the case.

2020-07-31 14:52 UTC, kathwill commented on hyrisecockpit/frontend/src/meta/names.ts
> +  const words = table.split("_");
I added a safeguard for these cases now

2020-07-31 15:01 UTC, schTi requested changes

2020-07-31 15:01 UTC, schTi commented on hyrisecockpit/frontend/src/meta/workloads.ts
> +    table.indexOf("tpch"),
I don't think that this will hold for the described cases. You should just return the plain table name, if none of the already defined workload names is included in the table name string. Otherwise our application will crash when the table name does not contain a '_'. This is what happened before I added the test exception

2020-07-31 15:04 UTC, kathwill commented on hyrisecockpit/frontend/src/meta/workloads.ts
> +    table.indexOf("tpch"),
But there is no table without a workload name included. Or do you have an example?

2020-07-31 15:12 UTC, Bouncner commented on hyrisecockpit/frontend/src/meta/workloads.ts
> +    table.indexOf("tpch"),
There might not be one right now, but the point of my request is that we should ensure that future workloads should still work even when they have multiple `_` them. Nobody knows how these table names will look like.

2020-07-31 15:15 UTC, kathwill commented on hyrisecockpit/frontend/src/meta/workloads.ts
> +    table.indexOf("tpch"),
If you mean `comp_cast_type.csv`, we receive this as `comp_cast_type_job_1` in the frontend. I can still add a return for your mentioned case, but I don't know if this is necessary.

2020-07-31 15:22 UTC, Bouncner commented on hyrisecockpit/frontend/src/meta/workloads.ts
> +    table.indexOf("tpch"),
No, I am talking about a file-based benchmark that we are going to add in some point in the future. Basically no one knows what the table names are going to be.

2020-07-31 15:26 UTC, kathwill commented on hyrisecockpit/frontend/src/meta/workloads.ts
> +    table.indexOf("tpch"),
@Bouncner Alright. I will change that. (My former answer was for @schTi, I didn't see your answer until now.)

2020-08-01 08:59 UTC, schTi approved these changes

2020-08-03 08:15 UTC, merged