B/add synchronous job handler
hyrise/Cockpit pull request #756
Opened 2020-09-07 14:00 UTC by Alexander-Dubrawski

This PR is the secound of four which aims to refactor the handling of Hyrise jobs (it aims to split #664). Hyrise jobs are interacting directly with the Hyrise to get the meta information and managing the Hyrise settings.  We have three kinds of jobs: 

1. jobs that need to be continuously in the background (for example: get the system information)
2. jobs that will be done asynchronously (for example: loading the tables)
3. jobs that are done synchronously (for example: sending a SQL query over the SQL endpoint)

Both continuous and asynchronous jobs are executed via the apscheduler (https://apscheduler.readthedocs.io/en/stable/). Esspacillay with the asynchronous jobs that's not necessary and increases the complexity (we could just use normal python threads). All three kinds of jobs are scattered in the database and background_scheduler component. The goal of the refactoring is now to have a clear separation for the jobs in the three categories (continuous, asynchronous, and synchronous) and define handlers for that. Moreover, we can stop the continuous jobs while loading/deleting tables (hyrise/hyrise#2180). 

This PR implements the handler for the synchronous jobs.

2020-10-12 17:59 UTC, Bensk1 requested changes
First round of comments, more tomorrow.

2020-10-12 17:59 UTC, Bensk1 commented on hyrisecockpit/database_manager/asynchronous_job_handler.py
> +        active_plugins = get_plugins_job(self._connection_factory)
`get_plugins_job` sounds like a function that returns a job. `active_plugins` sounds like a variable that holds plugin objects.

2020-10-12 17:59 UTC, Bensk1 commented on hyrisecockpit/database_manager/asynchronous_job_handler.py
> +        if active_plugins is None or plugin in active_plugins:
Does the second part match the documentation above? `False if database was blocked and job couldn't be started`.

2020-10-12 17:59 UTC, Bensk1 commented on hyrisecockpit/database_manager/database.py
> +        # TODO Move in background refactoring to scheduler
Is this todo intended?

2020-10-12 17:59 UTC, Bensk1 commented on hyrisecockpit/database_manager/job/execute_sql_query.py
> +    error_message: str
How's this different from database.py LL 21-30?

2020-10-12 17:59 UTC, Bensk1 commented on hyrisecockpit/database_manager/job/execute_sql_query.py
> +                    results=[[str(col) for col in row] for row in cur.fetchall()],
What is the original datatype of `col` before the cast?

2020-10-12 17:59 UTC, Bensk1 commented on hyrisecockpit/database_manager/job/execute_sql_query.py
> +        except Error as e:
Could we be more specific here? Also, is this error handled anywhere? There should be either proper handling or a crash.

2020-10-12 17:59 UTC, Bensk1 commented on hyrisecockpit/database_manager/job/get_detailed_plugins.py
> +        return [row[0].split("Plugin")[0] for row in rows]
A comment explaining the format of the string with an example could increase the readability here.

2020-10-12 17:59 UTC, Bensk1 commented on hyrisecockpit/database_manager/job/get_detailed_plugins.py
> +    """Return currently set plug-in settings.
Method name is singular, comment is plural.

2020-10-12 17:59 UTC, Bensk1 commented on hyrisecockpit/database_manager/job/get_detailed_plugins.py
> +    row[0].split("::")[1]. So for example from Plugin::Compression::MemorySetting we get Compression.
Good!

2020-10-12 17:59 UTC, Bensk1 commented on hyrisecockpit/database_manager/job/get_detailed_plugins.py
> +    }
I find this hard to read compared to a simple loop. Maybe you get a second opinion from @Bouncner. Is it correct to return an empty list on `else`?

2020-10-12 17:59 UTC, Bensk1 commented on hyrisecockpit/database_manager/job/get_loaded_tables_in_database.py
> +"""This job return all loaded tables in the database."""
returns

2020-10-12 17:59 UTC, Bensk1 commented on hyrisecockpit/database_manager/job/get_loaded_tables_in_database.py
> +    """Return already loaded tables."""
Maybe remove the `already`? "Return the database's current tables"?

2020-10-12 17:59 UTC, Bensk1 commented on hyrisecockpit/database_manager/job/get_loaded_tables_in_database.py
> +        return [row[0] for row in rows] if rows else []
Are we only extracting the names here?

2020-10-13 07:11 UTC, Bensk1 requested changes

2020-10-13 07:11 UTC, Bensk1 commented on hyrisecockpit/database_manager/job/get_workload_tables_status.py
> +            loaded = True
Would it be clearer to have this in the `else` branch?

2020-10-13 07:11 UTC, Bensk1 commented on hyrisecockpit/database_manager/job/get_workload_tables_status.py
> +            table = {
naming

2020-10-13 07:11 UTC, Bensk1 commented on hyrisecockpit/database_manager/synchronous_job_handler.py
> +class SqlResultInterface(TypedDict):
This seems familiar

2020-10-14 10:02 UTC, Alexander-Dubrawski commented on hyrisecockpit/database_manager/asynchronous_job_handler.py
> +        active_plugins = get_plugins_job(self._connection_factory)
How about to change `active_plugins` to `active_plugin_names` and `get_plugins_job ` to `get_active_plugin_names` ?

2020-10-14 10:04 UTC, Alexander-Dubrawski commented on hyrisecockpit/database_manager/asynchronous_job_handler.py
> +        if active_plugins is None or plugin in active_plugins:
The documentation is missing that the job returns false if the plugin is already active. I will adjust the documentation.

2020-10-14 10:17 UTC, Alexander-Dubrawski commented on hyrisecockpit/database_manager/job/execute_sql_query.py
> +                    results=[[str(col) for col in row] for row in cur.fetchall()],
It's a `tuple`. I will add the type.

2020-10-14 10:20 UTC, Alexander-Dubrawski commented on hyrisecockpit/database_manager/job/execute_sql_query.py
> +        except Error as e:
I will specify it to handle only database errors.

2020-10-14 10:30 UTC, Alexander-Dubrawski commented on hyrisecockpit/database_manager/job/execute_sql_query.py
> +        except Error as e:
We are already catching all `psycopg2` errors, so all database errors. Is that solution acceptable? We are catching all the following errors: https://www.psycopg.org/docs/errors.html

2020-10-14 10:52 UTC, Alexander-Dubrawski commented on hyrisecockpit/database_manager/job/get_detailed_plugins.py
> +    }
I will refactor this part. It is correct to return an empty list on `else`.

2020-10-14 11:03 UTC, Alexander-Dubrawski commented on hyrisecockpit/database_manager/job/get_loaded_tables_in_database.py
> +        return [row[0] for row in rows] if rows else []
Yes, we are extracting the table names. I will add a comment and adjust the SQL query to clarify it.

2020-10-14 11:08 UTC, Alexander-Dubrawski commented on hyrisecockpit/database_manager/job/get_workload_tables_status.py
> +            loaded = True
I'm not sure what exactly you are meaning. We need these variables in both cases `if` and `else` when we are returning `table`.

2020-10-19 13:01 UTC, Bensk1 commented on hyrisecockpit/database_manager/asynchronous_job_handler.py
> +        active_plugins = get_plugins_job(self._connection_factory)
Better!

2020-10-19 14:51 UTC, Bensk1 commented on hyrisecockpit/database_manager/job/execute_sql_query.py
> +                    results=[[str(col) for col in row] for row in results],
Still, why do we need the cast to `str` here?

2020-10-19 14:51 UTC, Bensk1 commented on hyrisecockpit/database_manager/job/get_detailed_plugins.py
> +        # ['Clustering']
Remove before merge

2020-10-19 14:52 UTC, Bensk1 commented on hyrisecockpit/database_manager/job/get_loaded_tables_in_database.py
> +        # ['region_tpch_0_1', 'customer_tpch_0_1']
see above

2020-10-19 14:53 UTC, Bensk1 approved these changes

2020-10-19 14:54 UTC, Bensk1 commented on hyrisecockpit/database_manager/job/execute_sql_query.py
> +        except Error as e:
Fine for me

2020-10-19 14:55 UTC, Bensk1 commented on hyrisecockpit/database_manager/job/get_workload_tables_status.py
> +            loaded = True
I was just referring to `loaded` but never mind, it's fine like that.

2020-10-20 07:39 UTC, Alexander-Dubrawski commented on hyrisecockpit/database_manager/job/execute_sql_query.py
> +                    results=[[str(col) for col in row] for row in results],
Inside the flask app, we are serializing and deserializing entities. We are doing that to make the code more robust. For example, if something changes in the response from the manager (database_manager/manager.py) we get an error.  Inside the IPC communication, we are using the JSON form for the messages. So that's why we are serializing and deserializing entities. In the case of a SQL result, we expect it to be a string (because the frontend expects the same). That's why we cast it. The python entities are defined by a model in this case it is defined in: 

https://github.com/hyrise/Cockpit/blob/dev/hyrisecockpit/api/app/sql/model.py

Inside the PR description of #775 I tried to describe how the serializing and deserializing is handled in our flask app.

2020-10-20 08:17 UTC, merged