B/add continuous background job handler
hyrise/Cockpit pull request #757
Opened 2020-09-07 14:01 UTC by Alexander-Dubrawski

This PR is the first of four which aims to refactor the handling of Hyrise jobs (it aims to split #664). Hyrise jobs are interacting directly with the Hyrise to get the meta information and managing the Hyrise settings.  We have three kinds of jobs: 

1. jobs that need to be continuously in the background (for example: get the system information)
2. jobs that will be done asynchronously (for example: loading the tables)
3. jobs that are done synchronously (for example: sending a SQL query over the SQL endpoint)

Both continuous and asynchronous jobs are executed via the apscheduler (https://apscheduler.readthedocs.io/en/stable/). Esspacillay with the asynchronous jobs that's not necessary and increases the complexity (we could just use normal python threads). All three kinds of jobs are scattered in the database and background_scheduler component. The goal of the refactoring is now to have a clear separation for the jobs in the three categories (continuous, asynchronous, and synchronous) and define handlers for that. Moreover, we can stop the continuous jobs while loading/deleting tables (hyrise/hyrise#2180). 

This PR implements the handler for continuous jobs.

2020-10-01 10:28 UTC, Bensk1 requested changes
Mostly comments regarding small typos in the documentation.

2020-10-01 10:28 UTC, Bensk1 commented on hyrisecockpit/database_manager/continuous_job_handler.py
> +                database. All connection relevant information (port, host) is
All information relevant for the connection...

2020-10-01 10:28 UTC, Bensk1 commented on hyrisecockpit/database_manager/continuous_job_handler.py
> +            hyrise_active: Flag stored in a shared memory map. This flag
responsive is different from active. Please rename or clarify.

2020-10-01 10:28 UTC, Bensk1 commented on hyrisecockpit/database_manager/continuous_job_handler.py
> +                database. All connection relevant information (port, host) is
see above

2020-10-01 10:28 UTC, Bensk1 commented on hyrisecockpit/database_manager/continuous_job_handler.py
> +        shutting it down.
`shut`

2020-10-01 10:28 UTC, Bensk1 commented on hyrisecockpit/database_manager/database.py
> +    influx database for the Hyrise instance.
an influx database for this Hyrise instance.

2020-10-01 10:28 UTC, Bensk1 commented on hyrisecockpit/database_manager/database.py
> +            id: A name representation of the Hyrise instance.
Sounds odd.

2020-10-01 10:28 UTC, Bensk1 commented on hyrisecockpit/database_manager/database.py
> +            password: The password needed to connects to the Hyrise instance.
`to connect`

2020-10-01 10:28 UTC, Bensk1 commented on hyrisecockpit/database_manager/database.py
> +            dbname: The database name of the Hyrise instance.
How does this differ from `id`. This should be clarified.

2020-10-01 10:28 UTC, Bensk1 commented on hyrisecockpit/database_manager/database.py
> +            number_workers: Number of task workers to put the Hyrise instance under
Under pressure sounds too specific. Workers just send queries to a hyrise instance, don't they?

2020-10-01 10:28 UTC, Bensk1 commented on hyrisecockpit/database_manager/database.py
> +            storage_host: Address in which the influx database is running.
Address of the influx database instance

2020-10-01 10:28 UTC, Bensk1 commented on hyrisecockpit/database_manager/database.py
> +        runs. Than we create a new database inside influx with the database id
Then

2020-10-01 10:28 UTC, Bensk1 commented on hyrisecockpit/database_manager/database.py
> +        (Hyrise). After that we create continuous query that the influx is running
a continuous

2020-10-01 10:28 UTC, Bensk1 commented on hyrisecockpit/database_manager/database.py
> +        every x seconds. For example it will so automatically calculate the throughput
For example, to automatically calculate...

2020-10-01 10:28 UTC, Bensk1 commented on hyrisecockpit/database_manager/database.py
> +        First we check if the workload and scale factor is valid.
First,

2020-10-01 10:28 UTC, Bensk1 commented on hyrisecockpit/database_manager/database.py
> +        For that workload need to have an equivalent driver and the
Not sure: For that workload, we need...?

2020-10-01 10:28 UTC, Bensk1 commented on hyrisecockpit/database_manager/database.py
> +        needs to be closed. If one of this requirements is not met the function
... is not met,...

2020-10-01 10:28 UTC, Bensk1 commented on hyrisecockpit/database_manager/database.py
> +        """
Is this comment an exact duplicate of the one of `load_data`?

2020-10-01 10:28 UTC, Bensk1 commented on tests/database_manager/test_continous_job_handler.py
> +    """This class test the continuous job handler."""
tests

2020-10-01 10:28 UTC, Bensk1 commented on tests/database_manager/test_continous_job_handler.py
> +        assert continuous_job_handler._scheduler == mock_background_scheduler_obj
Are these asserts the correct way for testing? If the asserts fail, the program crashes, doesn't it? I expected something like `assertEqual`

2020-10-05 10:25 UTC, Alexander-Dubrawski commented on tests/database_manager/test_continous_job_handler.py
> +        assert continuous_job_handler._scheduler == mock_background_scheduler_obj
This is the normal syntax for `pytest`. `pytest` is a third-party unit test framework with a more lighter-weight syntax. If an assert fails only the test fails.

2020-10-06 09:11 UTC, Bensk1 approved these changes

2020-10-06 13:27 UTC, merged