B/improve backend system tests
hyrise/Cockpit pull request #758
Opened 2020-09-09 12:53 UTC by Alexander-Dubrawski

This PR improves system tests. It is now possible to run the system test on the backend running in docker as well if it is running natively. Moreover, the tests are simplified. It is not necessary anymore to set up a second .env. All the environment variables are no defined in `docker.ini` and `native.ini`. 
The output of the containers/ components is logged in files, so it should help for debugging. 

## To do:

- [ ] Improve docstrings 
- [ ] Write a small guide on how to use the system tests.

2020-09-28 13:44 UTC, Bensk1 commented
I just read the guide in the wiki. First, good job, it seems understandable. Second, the introduction of the guide implies that there are two different system tests. Actually, it is the same system test, but the docker version is also starting a Hyrise and an InfluxDB instance, right? If I am correct this should be clarified as two different cases of the same system test.

2020-09-28 14:42 UTC, Bensk1 requested changes

2020-09-28 14:42 UTC, Bensk1 commented on system_tests/backend_handler.py
> +"""Handler to interact with back-end API."""
I don't know if my review comment would cause a lot of further changes but documentation/comments like `"""Handler to interact with back-end API."""` in a file called `backend_handler.py` do not really add value.

2020-09-28 14:42 UTC, Bensk1 commented on system_tests/settings.py
> +REQUEST_TIMEOUT: int = getenv("REQUEST_TIMEOUT", 5)  # type: ignore
What is the semantic of this? `getenv()` does return a string, correct? These constants should hold integers but they don't. Also, in the files that include settings.py we are calling, e.g., `int(REQUEST_TIMEOUT)`. Shouldn't we just use `int(getenv(...` to have correct type semantics, avoid the `type: ignore`` and avoid the `int(.` in the includers?

2020-09-28 14:42 UTC, Bensk1 commented on system_tests/test_backend.py
> +3. Start workload generation for TPC-H sf 0.1
For consistency `(SF 0.1)`

2020-09-28 14:42 UTC, Bensk1 commented on system_tests/test_backend.py
> +DEFAULT_TIME_OUT = int(DEFAULT_TIME_OUT)
See comment in settings.py

2020-09-28 14:42 UTC, Bensk1 commented on system_tests/test_backend.py
> +        This test is adding a database with the id test_database1.
See my comment regarding comments of self-descriptive code above.

2020-09-28 14:42 UTC, Bensk1 commented on system_tests/test_backend.py
> +        influx_databases = self.influx_client.get_list_database()
Since influx is a database system itself that could be confusing. Is this a list of Influx database systems or hyrise database systems stored inside influx?

2020-09-28 14:42 UTC, Bensk1 commented on system_tests/test_backend.py
> +        """Test loading TPC-H tables with scale factor 0_1."""
0.1

2020-09-28 14:42 UTC, Bensk1 commented on system_tests/test_backend.py
> +        self.check_tables_loading("test_database1", "tpch", 0.1)
I would think that `check_tables_loading` means that the tables are being loaded at the moment. The description in L154 sounds to me more like checking if the tables were loaded in the past. 

As a result, I would either change the method name (to `check_tables_loaded`) or the comment above.

2020-09-28 14:42 UTC, Bensk1 commented on system_tests/test_backend.py
> +        workload with the scale factor 0_1. It will publish 10 tasks
0.1

2020-09-28 14:42 UTC, Bensk1 commented on system_tests/test_backend.py
> +        now under pressure.
Under `load`. A Hyrise instance is never under pressure :)

2020-09-28 14:42 UTC, Bensk1 commented on system_tests/test_backend.py
> +        After a wait we check the metric data for throughput, latency
Minor: After a while

2020-09-28 14:42 UTC, Bensk1 commented on system_tests/test_backend.py
> +        THis tests checks if the Compression plug-in is returned correctly
`TH`

2020-09-28 14:42 UTC, Bensk1 commented on system_tests/test_backend.py
> +        THis tests checks if the Compression plug-in is returned correctly
Also, the sentence is hard to understand. I think I know what you mean but please rephrase it.

2020-09-28 14:42 UTC, Bensk1 commented on system_tests/test_backend.py
> +        was set correctly.
were

2020-09-28 14:42 UTC, Bensk1 commented on system_tests/backend_handler.py
> +    fails the test that called the method with the request fails.
If the timeout is exceeded, the test...

2020-09-28 14:42 UTC, Bensk1 commented on system_tests/backend_handler.py
> +        The URL needs to be adjusted with the start time stamp, end times stamp,
end time

2020-09-28 14:42 UTC, Bensk1 commented on system_tests/backend_handler.py
> +        and the precession.
precision

2020-09-28 14:42 UTC, Bensk1 commented on system_tests/backend_handler.py
> +        is activated on the database.
on the database -> for a specific database?

2020-09-28 14:42 UTC, Bensk1 commented on system_tests/test_docker_backend.py
> +    To make sure that the changes in the back-end code are taking into account,
To ensure that the changes of the back-end are taken into account, the back-end's docker container is always rebuilt from scratch.

2020-09-28 14:42 UTC, Bensk1 commented on system_tests/test_docker_backend.py
> +    teardown_class. The setup_class method is called before the System test (user scenario)
The inheritance and which methods are implemented can be easily obtained by looking at the source code.

2020-09-28 14:42 UTC, Bensk1 commented on system_tests/test_native_backend.py
> +    teardown_class. The setup_class method is called before the System test (user scenario)
see above

2020-09-28 14:42 UTC, Bensk1 commented on system_tests/test_native_backend.py
> +        This method starts back-end. After a wait time it will initialize
starts the back-end

2020-10-05 09:21 UTC, Alexander-Dubrawski commented
> I just read the guide in the wiki. First, good job, it seems understandable. Second, the introduction of the guide implies that there are two different system tests. Actually, it is the same system test, but the docker version is also starting a Hyrise and an InfluxDB instance, right? If I am correct this should be clarified as two different cases of the same system test.

Thanks for the feedback. I adjusted the guide.

2020-10-05 10:01 UTC, Alexander-Dubrawski commented on system_tests/backend_handler.py
> +"""Handler to interact with back-end API."""
I understand. We are using `pydocstyle` as a hook and this hook forces us by default to put everywhere a docstring. In my opinion, that's not really helpful. I will try to change the `pydocstyle` settings.  But I would like to do it in a separate PR if that ok for you?

2020-10-06 09:12 UTC, Bensk1 commented on system_tests/backend_handler.py
> +"""Handler to interact with back-end API."""
Sure!

2020-10-06 09:12 UTC, Bensk1 approved these changes

2020-10-06 12:42 UTC, merged