Adjust get plugin settings
hyrise/Cockpit pull request #765
Opened 2020-09-17 17:47 UTC by Alexander-Dubrawski

Since the `meta_settings` table inside the Hyrise was adjusted we needed to adjust the cockpit as well.

2020-09-17 19:55 UTC, Bouncner commented on tests/database_manager/test_database.py
> +                {"name": "MemoryBudget (MB)", "value": "55555", "description": "..."}
Space missing.

2020-09-17 19:55 UTC, Bouncner commented on tests/database_manager/test_database.py
> +            ("Plugin::Compression::MemoryBudget", "55555", "...", "MemoryBudget (MB)"),
Space ...

2020-09-17 20:23 UTC, Bensk1 commented on tests/database_manager/test_database.py
> +                {"name": "MemoryBudget (MB)", "value": "55555", "description": "..."}
Right, `Memory Budget (MB)`.

2020-09-17 20:25 UTC, Bensk1 requested changes

2020-09-17 20:25 UTC, Bensk1 commented on hyrisecockpit/database_manager/database.py
> +        The plug-in settings are obtained from the meta_settings tables in the hyrise instance.
table.

2020-09-17 20:25 UTC, Bensk1 commented on hyrisecockpit/database_manager/database.py
> +        row[0].split("::")[1]. So for example from Plugin::Compression::MemomrySetting we get Compression.
Memomry

2020-09-18 06:39 UTC, Bensk1 commented
I thought the docker container is automatically built when the Hyrise branch `bp1920` is updated.

2020-09-18 09:20 UTC, Alexander-Dubrawski commented
> I thought the docker container is automatically built when the Hyrise branch `bp1920` is updated.

At the moment we are building it manually. We could of course adjust Jenkins to build it for us, but actually I think it is easier to build it manually.  For example, if we change something in the Hyrise (rename the columns in a table) it could result in a failure of the cockpit. So it is easier to make the adjustments in the cockpit and than building the image manually.

2020-09-18 09:22 UTC, Bouncner approved these changes
LGTM.

2020-09-18 09:24 UTC, Bensk1 commented
Manually building it is fine for me for now. But I somehow thought that @cH3n7i said a new docker image would be built with each push to `bp1920`.

2020-09-18 09:25 UTC, Bensk1 approved these changes

2020-09-18 09:37 UTC, merged