Fix segment access Headmap
hyrise/Cockpit pull request #777
Opened 2020-10-26 17:00 UTC by Alexander-Dubrawski

This PR fixes the problem with the Segment Configuration.

Before this PR  the heatmap looked as followed:

![IMAGE 2020-09-18 18_21_24](https://user-images.githubusercontent.com/32880898/97202230-a339ef80-17b3-11eb-8028-d549036bda18.jpg)

To solve this Issue I adjusted the `monitor/segment_configuration` endpoint in the backend so that it returns the data in a form that is more suitable to build the heatmap. The *encoding type* and the *order type* mapped to an integer. The type can be found in a `mode_mapping` list inside the response to get the real value. For example 0 maps to Dictionary. This way the frontend can use the mapping List for the heat bar in the heatmap and doesn't need to do some extra calculations. 
As a result, I simplified the corresponding code inside the frontend.

Moreover, we can also use the heatmap to show the order mode of the columns. 

For that simply press this button: 

<img width="159" alt="Screenshot 2020-10-26 at 17 58 19" src="https://user-images.githubusercontent.com/32880898/97203367-fe201680-17b4-11eb-8e61-30a1f1053b91.png">

2020-10-26 17:06 UTC, Bouncner commented
Can you show the screenshots of the new UI?

2020-10-26 17:09 UTC, Alexander-Dubrawski commented
> Can you show the screenshots of the new UI?

![Screenshot 2020-10-26 at 18 09 29](https://user-images.githubusercontent.com/32880898/97204492-6fac9480-17b6-11eb-8f9b-5d4b2fce318a.png)

2020-10-26 18:54 UTC, Bouncner commented
Since there is no issue links: was that fix about changing x and y?

Can you name the y-axis "Chunk ID" and skip the "No."?
Is that mock data?

Concerning the axis, we could do something that starts at 30 degrees and goes up to 90 once there are more than 20 columns.

Looks good so far. Do you know how hard it would be to integrate the sorting information into the encoding graph? E.g. an arrow in each cell to denote "sorted"?

2020-10-26 19:11 UTC, Bouncner reviewed
Stopping for now to get your responses.

2020-10-26 19:11 UTC, Bouncner commented on .pydocstyle.ini
> +ignore = D100,D101,D102,D103,D104,D105,D106,D107,D203,D213
empty line to end, what are these?

2020-10-26 19:11 UTC, Bouncner commented on hyrisecockpit/database_manager/job/update_segment_configuration.py
> +def _execute_sql(sql: str, connection_factory: ConnectionFactory):
This looks like a function that should not be here (as well). I'd guess we have the same functionality already somewhere else?

2020-10-26 19:11 UTC, Bouncner commented on hyrisecockpit/database_manager/job/update_segment_configuration.py
> +from psycopg2 import DatabaseError, InterfaceError
Don't encapsulate the psycopg2 dependency somehow within a single file?

2020-10-26 19:11 UTC, Bouncner commented on hyrisecockpit/database_manager/job/update_segment_configuration.py
> +    for table_name, column in formatted_results.items():
Isn't the first loop `for table_name, column_id ...` and the second `for _, chunk_id ...`?

2020-10-26 19:11 UTC, Bouncner commented on hyrisecockpit/database_manager/job/update_segment_configuration.py
> +            formatted_mode = [mode[key] for key in sorted(mode)]
Please don't sort repeatedly.

2020-10-26 19:11 UTC, Bouncner commented on hyrisecockpit/database_manager/job/update_segment_configuration.py
> +            formatted_results[table_name][column_name] = formatted_mode
I can't follow. First, you create a dicts of dicts of dicts and now you overwrite the third layer with a list?

2020-10-26 19:11 UTC, Bouncner commented on hyrisecockpit/database_manager/job/update_segment_configuration.py
> +                                    ON meta_segments.table_name == meta_chunk_sort_orders.table_name
That `==` is no valid SQL.

2020-10-27 08:50 UTC, Alexander-Dubrawski commented
> Since there is no issue links: was that fix about changing x and y?

The fix goes a little bit deeper. In general, the frontend didn't read the data correctly and the backend didn't return the correct data. As a result, the data wasn't plotted correctly. 

> Can you name the y-axis "Chunk ID" and skip the "No."?
> Is that mock data?

Yes, I can adjust the naming. Data is not mocked.

> Concerning the axis, we could do something that starts at 30 degrees and goes up to 90 once there are more than 20 columns.

The Problem at the moment is that we are using DOM Objects that are kind of fixed and I wasn't able to find out how to manipulate their CSS properties. If we use an angle of 90 degrees the content would overflow and be cut off. But I will have a look again where I can find these properties. 

> Looks good so far. Do you know how hard it would be to integrate the sorting information into the encoding graph? E.g. an arrow in each cell to denote "sorted"?

I think in theory that should be possible but sadly I have not the knowledge to implement it. I could create an Issue for that.

2020-10-27 09:01 UTC, Alexander-Dubrawski commented on .pydocstyle.ini
> +ignore = D100,D101,D102,D103,D104,D105,D106,D107,D203,D213
The Pydocstyle hook can make some problems. If I, for example, ignore one rule then it can happen that as a result, I need to ignore multiple rules. Since I'm not really a fan of this hook I would like to remove it completely.

2020-10-27 09:06 UTC, Alexander-Dubrawski commented on hyrisecockpit/database_manager/job/update_segment_configuration.py
> +def _execute_sql(sql: str, connection_factory: ConnectionFactory):
Actually, you are right. Normally all the jobs are executing a SQL query that way.  If you want I can put this functionality in a job called `execute_sql.py`.

2020-10-27 09:08 UTC, Alexander-Dubrawski commented on hyrisecockpit/database_manager/job/update_segment_configuration.py
> +from psycopg2 import DatabaseError, InterfaceError
I'm not sure what exactly you mean. Can you be more specific 🙃  ? We only import the Error Type and not the hole model.

2020-10-27 09:16 UTC, Alexander-Dubrawski commented on hyrisecockpit/database_manager/job/update_segment_configuration.py
> +    for table_name, column in formatted_results.items():
We extracting the column name from the table so column id wouldn't be correct. But I agree that chunk_id in the secound loop would be better.

2020-10-27 09:23 UTC, Alexander-Dubrawski commented on hyrisecockpit/database_manager/job/update_segment_configuration.py
> +            formatted_mode = [mode[key] for key in sorted(mode)]
I want to make sure that the indexes of the list are in the right order. If we would have extraceted for example the following result: 

```python
formatted_results = {
    "lineitem_tpch_0_1": {
        "l_orderkey": {
            "1": 0,
            "0": 1,
            "2": 0,
        },
        "l_partkey": {
            "1": 1,
            "0": 1,
            "2": 1,
        },
    },
}

mode_id_mapping = ["Dictionary", "LZ4"]
```

we would need to sort the keys so that the indexes of the list are in the correct order. We are doing all of this so that the frontend can build the heatmap. The heatmap needs integer values (for the z-axis) and can not work with strings. Moreover, the frontend needs a mapping list to blot the heat bar. So it knows that for example in a list ["Dictionary", "LZ4"] all values with 0 get the color green all with the value 1 yellow and so on. In the heat bar for green would be Dictionary displayed and so on.

2020-10-27 09:23 UTC, Alexander-Dubrawski commented on hyrisecockpit/database_manager/job/update_segment_configuration.py
> +            formatted_results[table_name][column_name] = formatted_mode
Please refer to the comment above.

2020-10-27 09:24 UTC, Alexander-Dubrawski commented on hyrisecockpit/database_manager/job/update_segment_configuration.py
> +                                    ON meta_segments.table_name == meta_chunk_sort_orders.table_name
Yes, you are right.

2020-10-27 09:36 UTC, Bouncner commented on .pydocstyle.ini
> +ignore = D100,D101,D102,D103,D104,D105,D106,D107,D203,D213
What is a hook? What is "this hook"?

2020-10-27 10:16 UTC, Bouncner commented on hyrisecockpit/database_manager/job/update_segment_configuration.py
> +def _execute_sql(sql: str, connection_factory: ConnectionFactory):
That shouldn't be a job, that should be a function in a database handler/object/class. We shouldn't define such a basic function again and again.

2020-10-27 10:17 UTC, Bouncner commented on hyrisecockpit/database_manager/job/update_segment_configuration.py
> +from psycopg2 import DatabaseError, InterfaceError
Belongs to the discussion above. If we decide to go for another library (might happen, e.g., to get asynchronous queries or whatever), a lot of places need to be touched. This should be encapsulated.

2020-10-27 10:18 UTC, Bouncner commented on hyrisecockpit/database_manager/job/update_segment_configuration.py
> +    for table_name, column in formatted_results.items():
It's not just the naming. This looks wrong to me.

2020-10-27 10:19 UTC, Bouncner commented on hyrisecockpit/database_manager/job/update_segment_configuration.py
> +            formatted_mode = [mode[key] for key in sorted(mode)]
What would be the problem is the list is not sorted?

2020-10-27 10:19 UTC, Bouncner commented on hyrisecockpit/database_manager/job/update_segment_configuration.py
> +            formatted_results[table_name][column_name] = formatted_mode
The comment above doesn't help me.

2020-10-27 10:22 UTC, Bouncner commented
> The fix goes a little bit deeper. In general, the frontend didn't read the data correctly and the backend didn't return the correct data. As a result, the data wasn't plotted correctly

Ok, I see.
 
> > Is that mock data? 
> Yes, I can adjust the naming. Data is not mocked.

Then why is just every forth chunk shown? Or do we show them all but have only every forth shown in the in axis?
I think we definitely need a thin border in the table.

> The Problem at the moment is that we are using DOM Objects that are kind of fixed and I wasn't able to find out how to manipulate their CSS properties. If we use an angle of 90 degrees the content would overflow and be cut off. But I will have a look again where I can find these properties.

That should be straightforward. Nothing important for now, but if you cannot find it easily, please create a ticket.
Can you please check out some TPC-H and DS tables on a laptop screen? If 45 degrees works, I am fine with it for now.

> > Looks good so far. Do you know how hard it would be to integrate the sorting information into the encoding graph? E.g. an arrow in each cell to denote "sorted"?
> 
> I think in theory that should be possible but sadly I have not the knowledge to implement it. I could create an Issue for that.

Yes, please create an issue.

2020-10-27 10:58 UTC, Alexander-Dubrawski commented on .pydocstyle.ini
> +ignore = D100,D101,D102,D103,D104,D105,D106,D107,D203,D213
We are running these hooks in every commit. For more information please refer to https://github.com/hyrise/Cockpit/wiki/Development-Environment-Setup#Hooks .

2020-10-27 11:44 UTC, Alexander-Dubrawski commented on hyrisecockpit/database_manager/job/update_segment_configuration.py
> +def _execute_sql(sql: str, connection_factory: ConnectionFactory):
The functionality is defined in the `connection` that we get from the `connection factory`:

https://github.com/hyrise/Cockpit/blob/dev/hyrisecockpit/database_manager/cursor.py

We still need to use the context manager, so that the cursor is closed properly.

2020-10-27 11:47 UTC, Alexander-Dubrawski commented on hyrisecockpit/database_manager/job/update_segment_configuration.py
> +from psycopg2 import DatabaseError, InterfaceError
We handle the errors differently across the backend. We could try to move the Error handling insider the cursor, but I would prefer to do it in a separate PR or create an issue for the moment.

2020-10-27 11:47 UTC, Alexander-Dubrawski commented on hyrisecockpit/database_manager/job/update_segment_configuration.py
> +            formatted_results[table_name][column_name] = formatted_mode
I will rework it.

2020-10-27 11:50 UTC, Alexander-Dubrawski commented on hyrisecockpit/database_manager/job/update_segment_configuration.py
> +            formatted_mode = [mode[key] for key in sorted(mode)]
Then in the heat map, we would display the wrong information for the wrong chunk. The index of the list defines the chunk id. Like I said before this endpoint is adjusted to work with the plotting of the heatmap in the frontend. The endpoint by itself and not in connection with the frontend might seem a little bit strange.

2020-10-27 11:52 UTC, Alexander-Dubrawski commented on hyrisecockpit/database_manager/job/update_segment_configuration.py
> +    for table_name, column in formatted_results.items():
If we can guarantee that the chunk id is ascending in the response of the Hyrise I can build the list directly and we don't need to convert a dict to a list. But the way how it is implemented now we can be sure that the encoding and order is indexed correctly to the chunks.

2020-10-27 13:39 UTC, Bensk1 commented on hyrisecockpit/database_manager/job/update_segment_configuration.py
> +    for table_name, column in formatted_results.items():
You can guarantee that by using `ORDER BY`, can't you?

2020-11-02 11:00 UTC, Alexander-Dubrawski commented on hyrisecockpit/database_manager/job/update_segment_configuration.py
> +    for table_name, column in formatted_results.items():
That's a good point. `ORDER BY` should work as well. I will change it.

2020-11-02 17:59 UTC, Alexander-Dubrawski commented
> Ok, I see.
> 
> > > Is that mock data?
> > > Yes, I can adjust the naming. Data is not mocked.
> 
> Then why is just every forth chunk shown? Or do we show them all but have only every forth shown in the in axis?
> I think we definitely need a thin border in the table.
>> that's a good point. I will look into it.

2020-11-09 19:58 UTC, Bouncner commented on hyrisecockpit/database_manager/job/update_segment_configuration.py
> +def _execute_sql(sql: str, connection_factory: ConnectionFactory):
I don't see anything somewhat related to the segment configuration view. So why should we have that method here? If we move it, we could also get rid of the psyco imports.

2020-11-09 19:58 UTC, Bouncner commented on hyrisecockpit/frontend/src/meta/metrics.ts
> +    yaxis: "Chunks ID",
Chunk ID.

2020-11-09 20:00 UTC, Bouncner commented on hyrisecockpit/frontend/tests/e2e/specs/metrics/access.spec.ts
> +const layout = { xtitle: "Columns", ytitle: "Chunks ID" };
Chunk ID

2020-11-10 07:48 UTC, Bensk1 commented on hyrisecockpit/frontend/src/components/charts/Heatmap.vue
> +        tickformat: ",d",
Does that mean "comma separated decimal"? Maybe add a comment then.

2020-11-10 07:48 UTC, Bensk1 commented on hyrisecockpit/frontend/src/components/metrics/SegmentConfiguration.vue
> +          `<b>segment: %{x}</b> <br>${selection.selectedType.value}: %{text} <extra></extra>`
What is `x`?

2020-11-10 07:48 UTC, Bensk1 commented on hyrisecockpit/database_manager/job/update_segment_configuration.py
> +    the keys are the tables names. For every table name the value is a
`table names` (preferred) or `tables' names`

2020-11-10 07:48 UTC, Bensk1 commented on hyrisecockpit/database_manager/job/update_segment_configuration.py
> +    the mode. The mode can be for example "Dictionary",
Instead of `mode` something like `...name of the configuration`?

2020-11-10 07:48 UTC, Bensk1 commented on hyrisecockpit/database_manager/job/update_segment_configuration.py
> +    We can build this list with a loop since the chunks are
This chunk order is a hard requirement, isn't it? In that case, I would place this comment right at the loop to avoid it getting overseen in the middle of this comment block. Also, should we (debug-)assert that ordering?

2020-11-10 07:48 UTC, Bensk1 commented on hyrisecockpit/database_manager/job/update_segment_configuration.py
> +    We use this list to make it easier in the frontend to build the headmap.
The last sentence (`We use this list...`) does not add any value and could be omitted.

2020-11-10 07:48 UTC, Bensk1 commented on hyrisecockpit/database_manager/job/update_segment_configuration.py
> +    are formatted to a dictionary they are written to the influx.
`to a dictionary and are written to InfluxDB`?

2020-11-10 07:48 UTC, Bensk1 commented on hyrisecockpit/database_manager/job/update_segment_configuration.py
> +    meta_segments table.
Not sure whether this is necessary or directly visible from the SQL statements.

2020-11-10 13:19 UTC, Alexander-Dubrawski commented
@Bensk1 @Bouncner here is a screenshot of the implementation, what do you think? An angle of 45 degrees seems to work for the moment. 

<img width="1252" alt="Screenshot 2020-11-10 at 14 17 33" src="https://user-images.githubusercontent.com/32880898/98679010-ac07f500-235f-11eb-9374-dfd1f05c00a1.png">

2020-11-10 13:56 UTC, Bouncner commented
Angle looks good, but I need to see it with a margin between the cells to make my final verdict.

2020-11-10 14:02 UTC, Alexander-Dubrawski commented
> Angle looks good, but I need to see it with a margin between the cells to make my final verdict.

What exactly do you mean by the margin between the calls? do you mean the margin between the xlabels?

2020-11-10 14:06 UTC, Bouncner commented
White space between the cells. I cannot find the review comment, but I mentioned it earlier. It shouldn't be a green large rectable, but many green ones. Otherwise nobody understands why the chunk ID show up  like "0, 4, 8, 12".

2020-11-10 14:06 UTC, Alexander-Dubrawski commented on hyrisecockpit/frontend/src/components/metrics/SegmentConfiguration.vue
> +          `<b>segment: %{x}</b> <br>${selection.selectedType.value}: %{text} <extra></extra>`
Its the x value.

2020-11-10 18:16 UTC, Alexander-Dubrawski commented
> White space between the cells. I cannot find the review comment, but I mentioned it earlier. It shouldn't be a green large rectable, but many green ones. Otherwise nobody understands why the chunk ID show up like "0, 4, 8, 12".

Ok, I will look into it.

2020-11-10 19:39 UTC, Alexander-Dubrawski commented
> White space between the cells

@Bouncner what do you think about the following heatmap: 

<img width="1229" alt="Screenshot 2020-11-10 at 20 36 26" src="https://user-images.githubusercontent.com/32880898/98724891-ad074980-2394-11eb-8a50-72d9e03163d0.png">

I will try to remove that strange horizontal line that is starting from y 0.

2020-11-11 08:22 UTC, Bensk1 commented
Fine for me!

2020-11-11 08:45 UTC, Alexander-Dubrawski commented on hyrisecockpit/frontend/src/components/metrics/SegmentConfiguration.vue
> +          `<b>segment: %{x}</b> <br>${selection.selectedType.value}: %{text} <extra></extra>`
So for example the name of the segment.

2020-11-11 09:24 UTC, Bouncner commented
Looks superb. BUT I still would like to see the result for TPC-H SF 1 and table lineitem after the compression plugin was activated. Because that's basically what this whole heatmap is for.

Sorry for the work. ;)

2020-11-11 16:32 UTC, Alexander-Dubrawski commented
> Looks superb. BUT I still would like to see the result for TPC-H SF 1 and table lineitem after the compression plugin was activated. Because that's basically what this whole heatmap is for.

That's how it looks on my MacBook (2560 x 1600)

<img width="1237" alt="Screenshot 2020-11-11 at 17 29 00" src="https://user-images.githubusercontent.com/32880898/98837885-cddaa800-2443-11eb-93a1-670c117eac30.png">

And that's how it looks on my 4k Monitor: 

<img width="2363" alt="Screenshot 2020-11-11 at 17 29 40" src="https://user-images.githubusercontent.com/32880898/98837917-d8953d00-2443-11eb-90d7-fab4751413b0.png">

2020-11-11 17:16 UTC, Bouncner commented
The compression plugin.

2020-11-14 09:19 UTC, Alexander-Dubrawski commented
> The compression plugin.

How do you like it? Beautiful isn't it? 🙃 

![Screenshot 2020-11-14 at 10 17 22](https://user-images.githubusercontent.com/32880898/99144023-ca713780-2662-11eb-8171-73449fd3e2fe.png)

2020-11-14 09:24 UTC, Bouncner commented
😍

2020-11-14 10:10 UTC, Bensk1 commented
That looks great, thanks!

2020-11-14 10:25 UTC, Bouncner requested changes

2020-11-14 10:25 UTC, Bouncner commented on hyrisecockpit/database_manager/job/update_segment_configuration.py
> +    The name of the configuration is represented by an integer.
Not configuration, “encoding”.
What if Chunk ID 0 does not exist?

2020-11-14 10:53 UTC, Alexander-Dubrawski commented on hyrisecockpit/database_manager/job/update_segment_configuration.py
> +    The name of the configuration is represented by an integer.
We use the same function for getting the order. That's why I used `configuration `. Can it happen that the `meta_segments` tables are missing some Chunk IDs? If some Chunk Ids are missing (and so the chunks itself) nothing would break, but we would assign the chunks the wrong ID.

2020-11-15 20:43 UTC, Bouncner commented on hyrisecockpit/database_manager/job/update_segment_configuration.py
> +    The name of the configuration is represented by an integer.
Yes, chunks might be deleted. Since we are going to have "self-driving" plugins that regularly delete chunks, we should consider fixing this.
@Bensk1 : shall we open an issue? It's important, but the deadline is approaching.

2020-11-15 20:45 UTC, Bouncner commented on hyrisecockpit/database_manager/job/update_segment_configuration.py
> +    The name of the configuration is represented by an integer.
And concerning "configuration". Could we use "property"? We use the term configuration in the index selection, compression selection and elsewhere, where is describes the whole system. So it's confusing to use it here as well.

2020-11-16 08:39 UTC, Alexander-Dubrawski commented on hyrisecockpit/database_manager/job/update_segment_configuration.py
> +    The name of the configuration is represented by an integer.
I can try to fix it.

2020-11-16 09:23 UTC, Alexander-Dubrawski commented on hyrisecockpit/database_manager/job/update_segment_configuration.py
> +    The name of the configuration is represented by an integer.
I wrote a fix for this problem. Which plugin deletes chunks ? I still need to make sure that this fix is working with the frontend as well (In theory it should work).

2020-11-16 10:56 UTC, Bouncner approved these changes
Just the missing implementation of the aggregation query. As soon as this is implemented and tested, we can merge.

2020-11-16 11:00 UTC, Alexander-Dubrawski commented
> Just the missing implementation of the aggregation query. As soon as this is implemented and tested, we can merge.

Do you mean the query for the #776 PR? 🙃

2020-11-16 14:59 UTC, merged